import burgundyFabric from "../../assets/images/samples/piece-1.jpg";
import goldFabric from "../../assets/images/samples/piece-2.jpg";
import roseFabric from "../../assets/images/samples/piece-3.jpg";

export const CHAT_MEDIA = { burgundyFabric, goldFabric, roseFabric };

export const MOCK_THREADS = [
  {
    id: "order-udc-2048",
    kind: "order",
    title: "Auntie Kemi’s Wedding",
    label: "Main Order",
    orderNumber: "UDC-2048",
    status: "Awaiting Customer Review",
    assignedTo: "Dicta Couturier",
    unread: 2,
    lastActivity: "10:32 AM",
    lastMessage: "Your updated Order Card is ready for review.",
    currentPin: {
      type: "order",
      label: "Current Pin",
      title: "Order Card · Edition 2",
      meta: "Awaiting Customer Review",
    },
    messages: [
      {
        id: "o1",
        type: "system",
        text: "This chat is the working conversation for Main Order UDC-2048.",
      },
      {
        id: "o2",
        type: "customer",
        text: "Good morning. Please make the blouse a little longer, just like we discussed.",
        time: "10:24 AM",
        state: "sent",
      },
      {
        id: "o3",
        type: "couturier",
        text: "Of course. I’ve updated the blouse length and prepared the new Edition for you to review.",
        time: "10:26 AM",
      },
      {
        id: "o4",
        type: "orderCard",
        orderNumber: "UDC-2048",
        edition: "Edition 2 (Current)",
        state: "Awaiting Customer Review",
        title: "Auntie Kemi’s Wedding",
        productName: "Royal Burgundy Aso Oke Fabric",
        image: burgundyFabric,
        serviceType: "Fabric & Sew",
        quantity: "2 bundles",
        total: "₦250,000",
      },
      {
        id: "o5",
        type: "couturier",
        text: "I also attached the current fabric reference so everything stays in one place.",
        time: "10:31 AM",
      },
      {
        id: "o6",
        type: "media",
        images: [burgundyFabric, roseFabric, goldFabric],
        time: "10:32 AM",
      },
      {
        id: "o7",
        type: "customer",
        text: "Perfect. I’ll review the current Edition now.",
        time: "10:35 AM",
        state: "sent",
      },
    ],
  },

  {
    id: "order-udc-2031",
    kind: "order",
    title: "Brother Bolu’s Birthday",
    label: "Main Order",
    orderNumber: "UDC-2031",
    status: "Completed",
    assignedTo: "Dicta Couturier",
    unread: 0,
    lastActivity: "18 Sep",
    lastMessage: "This order is complete and remains available as history.",
    currentPin: null,
    messages: [
      { id: "b1", type: "system", text: "Main Order UDC-2031 is completed. This conversation remains available as transaction history." },
      { id: "b2", type: "couturier", text: "Your order has been completed. Thank you for choosing UNIVERSAL DICTA COUTURE.", time: "5:14 PM" },
      { id: "b3", type: "customer", text: "Thank you. Everything came out beautifully.", time: "5:18 PM", state: "sent" },
    ],
  },
  {
    id: "order-udc-2026",
    kind: "order",
    title: "UDC-2026",
    label: "Main Order",
    orderNumber: "UDC-2026",
    status: "Payment Completed · Fulfilment ongoing",
    assignedTo: "Dicta Couturier",
    unread: 0,
    lastActivity: "10 Sep",
    lastMessage: "Payment is complete. The order is still active until fulfilment is completed.",
    currentPin: { type: "order", label: "Current Pin", title: "Order Card · Edition 1", meta: "Payment Completed" },
    messages: [
      { id: "c1", type: "system", text: "Payment Completed does not automatically mean Order Completed." },
      { id: "c2", type: "couturier", text: "Your payment has been verified. We’ll continue to keep this chat active while fulfilment is ongoing.", time: "12:45 PM" },
      { id: "c3", type: "customer", text: "Perfect, thank you for the update.", time: "12:48 PM", state: "sent" },
    ],
  },
  {
    id: "general-guidance",
    kind: "general",
    title: "General guidance",
    label: "Free chat",
    status: "No Main Order attached",
    assignedTo: "Dicta Couturier",
    unread: 0,
    lastActivity: "Yesterday",
    lastMessage: "Burgundy and gold can both work beautifully.",
    context: {
      type: "product",
      title: "You’re asking about this product",
      name: "Burgundy Aso Oke Fabric",
      meta: "Public product reference · no order created",
      image: burgundyFabric,
    },
    messages: [
      {
        id: "g1",
        type: "context",
        contextType: "product",
        title: "You’re asking about this product",
        name: "Burgundy Aso Oke Fabric",
        meta: "Public product reference · no Main Order attached",
        image: burgundyFabric,
      },
      {
        id: "g2",
        type: "customer",
        text: "Hi, I’m choosing colours for a family celebration. Can you guide me before I order anything?",
        time: "4:08 PM",
        state: "sent",
      },
      {
        id: "g3",
        type: "couturier",
        text: "Absolutely. You can ask anything here first. A Main Order is only created when you actually decide to proceed with an order.",
        time: "4:11 PM",
      },
      {
        id: "g4",
        type: "customer",
        text: "I’m between burgundy and gold. I want something rich but not too loud.",
        time: "4:15 PM",
        state: "sent",
      },
      {
        id: "g5",
        type: "couturier",
        text: "Burgundy will feel deeper and more formal, while gold feels brighter. We can keep this as a normal guidance chat while you decide.",
        time: "4:18 PM",
      },
    ],
  },
  {
    id: "closet-review",
    kind: "general",
    title: "Selected My Closet pieces",
    label: "My Closet context",
    status: "Structured review context",
    assignedTo: "Dicta Couturier",
    unread: 0,
    lastActivity: "Now",
    lastMessage: "Your selected pieces are attached as mock review context.",
    context: {
      type: "product",
      title: "You’re reviewing selected My Closet pieces",
      name: "Structured multi-piece context",
      meta: "Mock selection context · no payment or completed order created",
      image: burgundyFabric,
    },
    messages: [
      {
        id: "m1",
        type: "context",
        contextType: "product",
        title: "Selected from My Closet",
        name: "Structured multi-piece review context",
        meta: "Your selected fabrics stay saved while you discuss them with a Couturier.",
        image: burgundyFabric,
      },
      {
        id: "m2",
        type: "couturier",
        text: "I can see the pieces you selected from My Closet. We can discuss them here before any Main Order is created.",
        time: "Now",
      },
    ],
  },
  {
    id: "review-context",
    kind: "general",
    title: "Review inspiration",
    label: "Review context",
    status: "Public-safe reference only",
    assignedTo: "Dicta Couturier",
    unread: 0,
    lastActivity: "Mon",
    lastMessage: "I can help you create your own order from this inspiration.",
    context: {
      type: "review",
      title: "You’re asking about this review",
      name: "Burgundy wedding Dicta Moment",
      meta: "Public-safe reference · reviewer’s private order is not attached",
      image: roseFabric,
    },
    messages: [
      {
        id: "r1",
        type: "context",
        contextType: "review",
        title: "You’re asking about this review",
        name: "Burgundy wedding Dicta Moment",
        meta: "Public-safe reference only · no private reviewer data follows this card",
        image: roseFabric,
      },
      {
        id: "r2",
        type: "customer",
        text: "I like the overall burgundy direction in this Dicta Moment. Can I do something inspired by it?",
        time: "2:20 PM",
        state: "sent",
      },
      {
        id: "r3",
        type: "couturier",
        text: "Yes. I can guide you using only the public-safe reference. If you decide to proceed, we’ll create your own Main Order — never the original reviewer’s private transaction.",
        time: "2:24 PM",
      },
    ],
  },
];
