import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {initializeApp,deleteApp} from 'firebase-admin/app';
import {getAuth} from 'firebase-admin/auth';
import {getFirestore} from 'firebase-admin/firestore';
import {createAccountService} from '../netlify/lib/account-service.js';
import {createTransactionService} from '../netlify/lib/transaction-service.js';
import {createOrderWorkspace} from '../netlify/lib/order-workspace.js';
import {createOrderGovernance} from '../netlify/lib/order-governance.js';
import {editionDifferences,frozenOrderCommand,nextOrderAction,targetStillCurrent} from '../src/services/orderWorkspaceModel.js';
import {canDiscover} from '../src/services/staffAuthorization.js';
import {operationalSummary} from '../src/services/operationsModel.js';
import {safeContextCapsule,resolveOperationalOpen} from '../src/services/operationalActions.js';
const id=()=>randomUUID();
let app,db,auth,account,owner,transactions,workspace,governance,staff,limited,orderId,terms;
async function member(caps){const uid=id(),staffId=id();await db.doc('admins/'+uid).set({staffId,active:true,functionAsCouturier:true,eligible:true,available:true,capabilities:caps});await db.doc('staffIdentities/'+staffId).set({staffId,principalUid:uid,active:true});return{uid,staffId,kind:'staff',auth_time:Math.floor(Date.now()/1000)};}
const grant=_action=>({domainWide:{active:true,purpose:'order-operations'}});
async function commercial(action,extra={}){const current=await transactions.readOrder(staff,orderId),work=(await db.doc(`orders/${orderId}/work/base`).get()).data();return transactions.commercial(staff,{orderId,componentId:'base',expectedVersion:current.version,expectedEdition:current.currentEdition,expectedWorkingVersion:work.workingVersion,operationId:id(),action,...extra});}
before(async()=>{
  process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8089';process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099';process.env.METADATA_SERVER_DETECTION='none';
  app=initializeApp({projectId:'demo-udc-section12'},'s14-'+id());db=getFirestore(app);auth=getAuth(app);account=createAccountService({db,auth,secret:'local-section14-test-only-secret'});transactions=createTransactionService(account);workspace=createOrderWorkspace(transactions);governance=createOrderGovernance(transactions);
  const email=`s14-${id()}@example.test`;await account.register({email,password:'Section14-Local-Only!',operationId:id()});const user=await auth.getUserByEmail(email);owner={uid:user.uid,auth_time:Math.floor(Date.now()/1000)};
  staff=await member(Object.fromEntries(['read','save-working','establish-edition','business-approve','claim','transfer','undo-working'].map(action=>['orders.'+action,grant(action)])));
  const productId=id();await db.doc('products/'+productId).set({_ownerVersion:2,_version:1,publicVersion:1,status:'published',publishedAt:Date.now(),publicRepresentation:{name:'Synthetic Section14 Aso Oke',price:1000,unitLabel:'per piece',category:['Fabric'],images:[{url:'https://example.test/approved-public.jpg'}]}});
  const created=await transactions.catalogueOrder(owner,{operationId:id(),items:[{productId,quantity:1,selections:{},expectedPublicVersion:1}]});orderId=created.orderId;
  await commercial('establish-edition');terms=(await transactions.readOrder(staff,orderId)).edition;
  limited=await member({'orders.read':{selectedObject:{active:true,purpose:'order-operations',ids:[orderId]}}});
});
after(async()=>{await db?.terminate();await deleteApp(app);});
test('S14 source composition preserves stable Main Order, Current Work, exact Edition and one Chat',async()=>{const current=await workspace.read(staff,orderId);assert.equal(current.orderId,orderId);assert.equal(current.currentWork,'base');assert.equal(current.currentEdition,1);assert.equal(current.chatId,'order:'+orderId);assert.equal(current.fulfilment,'NOT STARTED');assert.equal(current.completed,false);assert.ok(!Object.hasOwn(current,'originalSnapshot'));assert.ok(!Object.hasOwn(current,'accountId'));});
test('S14 general/assigned Order access does not disclose private delivery, issue reasons, working changes or proof',async()=>{await db.doc(`orders/${orderId}/work/base`).update({deliveryContext:{address:'PRIVATE SYNTHETIC ADDRESS'},issues:{sample:{kind:'HOLD',reason:'PRIVATE INTERNAL REASON',resolved:false}}});const current=await workspace.read(limited,orderId);assert.ok(!Object.hasOwn(current,'working'));assert.ok(!Object.hasOwn(current,'deliveryContext'));assert.ok(!Object.hasOwn(current,'operational'));assert.ok(!JSON.stringify(current).includes('PRIVATE'));assert.deepEqual(current.actions,[]);await assert.rejects(workspace.payments(limited,orderId),{code:'permission-denied'});await assert.rejects(workspace.original(limited,orderId),{code:'permission-denied'});});
test('S14 private operational and delivery disclosure requires independent complete DataPurpose routes',async()=>{const path=db.doc('admins/'+limited.uid),raw=(await path.get()).data();await path.update({capabilities:{...raw.capabilities,'orders.delivery-read':{dataPurpose:{active:true,purpose:'order-operations',ids:[orderId],dataClasses:['delivery-context']}},'orders.operations-read':{dataPurpose:{active:true,purpose:'order-operations',ids:[orderId],dataClasses:['operational-context']}}}});const current=await workspace.read(limited,orderId);assert.equal(current.deliveryContext.address,'PRIVATE SYNTHETIC ADDRESS');assert.equal(current.operational.issues.sample.reason,'PRIVATE INTERNAL REASON');assert.ok(!Object.hasOwn(current,'working'));});
test('S14 Original Snapshot is lazy, immutable and minimum-safe; mutable Product/Profile is not returned as Ordered As',async()=>{const path=db.doc('admins/'+staff.uid),raw=(await path.get()).data();await path.update({capabilities:{...raw.capabilities,'orders.origin-read':{dataPurpose:{active:true,purpose:'order-operations',ids:[orderId],dataClasses:['order-origin']}}}});const original=await workspace.original(staff,orderId);assert.equal(original.state,'captured');assert.equal(original.entries[0].label,'Synthetic Section14 Aso Oke');assert.ok(!Object.hasOwn(original,'customer'));assert.ok(!Object.hasOwn(original,'delivery'));await db.doc('products/'+original.entries[0].productId).update({'publicRepresentation.name':'Later Product Now'});assert.deepEqual(await workspace.original(staff,orderId),original);});
test('S14 payment summary access is independent from proof/verification and preserves append-oriented records',async()=>{const paymentId=id();await db.doc('payments/'+paymentId).set({paymentId,orderId,componentId:'base',version:1,state:'NEEDS ATTENTION',amountMinor:10000,proofReferenceId:'PRIVATE-PROOF',submittedAt:Date.now()});const path=db.doc('admins/'+limited.uid),raw=(await path.get()).data();await path.update({capabilities:{...raw.capabilities,'payments.read':{selectedObject:{active:true,purpose:'payment-operations',ids:[orderId]}}}});const ledger=await workspace.payments(limited,orderId);assert.equal(ledger.records.length,1);assert.equal(ledger.records[0].paymentState,'NEEDS ATTENTION');assert.ok(!JSON.stringify(ledger).includes('PRIVATE-PROOF'));await assert.rejects(transactions.paymentDetail(limited,paymentId),{code:'permission-denied'});});
test('S14 authorized queue filtering happens before count/payload; missing results are not claimed complete',async()=>{const result=await workspace.queue(limited);assert.equal(result.complete,false);assert.equal(result.count,result.records.length);assert.ok(result.records.every(record=>record.orderId===orderId));assert.ok(!JSON.stringify(result).includes('PRIVATE'));});
test('S14 assignment-derived queue discovery stays exact and authority is recalculated after transfer',async()=>{const assigned=await member({'orders.read':{assignmentDerived:{active:true,purpose:'order-operations'}}});await db.doc('orders/'+orderId).update({assignedStaffId:assigned.staffId});assert.ok((await workspace.queue(assigned)).records.some(row=>row.orderId===orderId));assert.equal(canDiscover({active:true,staffId:assigned.staffId,functionAsCouturier:true,eligible:true,capabilities:{'orders.read':{assignmentDerived:{active:true,purpose:'order-operations'}}}},'orders'),true);await db.doc('orders/'+orderId).update({assignedStaffId:staff.staffId});await assert.rejects(workspace.read(assigned,orderId),{code:'permission-denied'});assert.ok(!(await workspace.queue(assigned)).records.some(row=>row.orderId===orderId));});
test('S14 no-semantic-change establishment preserves current Edition and approvals',async()=>{await commercial('business-approve');const before=await transactions.readOrder(staff,orderId);await commercial('save-working',{terms:{entries:terms.entries,amountDueNowMinor:terms.amountDueNowMinor,notes:terms.notes}});await assert.rejects(commercial('establish-edition'),{code:'no-semantic-change'});const after=await transactions.readOrder(staff,orderId);assert.equal(after.currentEdition,before.currentEdition);assert.deepEqual(after.businessApproval,before.businessApproval);await commercial('undo-working');});
test('S14 frozen confirmation cannot silently retarget a newer source/Edition/work',()=>{const source={orderId:'order-a',componentId:'base',version:4,currentEdition:2};const target=frozenOrderCommand(source,'business-approve');assert.equal(targetStillCurrent(target,source),true);for(const delta of [{version:5},{currentEdition:3},{componentId:'ext-a'},{orderId:'order-b'}])assert.equal(targetStillCurrent(target,{...source,...delta}),false);assert.equal(target.expectedEdition,2);assert.ok(Object.isFrozen(target));});
test('S14 deterministic difference lens uses Entry root, not ordinal; missing/duplicate evidence is incomplete',()=>{const a={rootId:'a',label:'A',quantity:1,unitAmountMinor:100,options:{b:2,a:1}},b={rootId:'b',label:'B',quantity:2,unitAmountMinor:200};assert.equal(editionDifferences({entries:[a,b]},{entries:[b,{...a,options:{a:1,b:2}}]}).state,'unchanged');const difference=editionDifferences({entries:[a,b]},{entries:[{...a,quantity:3}]}).records;assert.ok(difference.some(row=>row.rootId==='a'&&row.field==='quantity'));assert.ok(difference.some(row=>row.rootId==='b'&&row.state==='removed'));assert.equal(editionDifferences(null,{entries:[a]}).state,'incomplete');assert.equal(editionDifferences({entries:[a,a]},{entries:[a]}).state,'incomplete');});
test('S14 Next Action separates Customer approval, Payment Enablement, fulfilment, delivery and explicit completion',()=>{const base={currentEdition:2,componentId:'base',businessApproval:{edition:2},customerApproval:{edition:2},paymentEnabled:{edition:2},amountDueNowMinor:0,assignedStaffId:'staff',fulfilment:'NOT STARTED',delivery:'NOT PREPARED'};assert.equal(nextOrderAction({...base,customerApproval:null}).state,'waiting');assert.equal(nextOrderAction({...base,paymentEnabled:null}).action,'enable-payment');assert.equal(nextOrderAction({...base,amountDueNowMinor:null}).state,'checking');assert.equal(nextOrderAction(base).action,'start-fulfilment');assert.equal(nextOrderAction({...base,fulfilment:'IN FULFILMENT',delivery:'DELIVERED'}).action,'complete');assert.equal(nextOrderAction({...base,completed:true}).state,'terminal');});
test('S14 revocation fails closed on reread, including exact protected deep links',async()=>{await db.doc('admins/'+limited.uid).update({active:false});for(const read of [()=>workspace.read(limited,orderId),()=>workspace.queue(limited),()=>workspace.payments(limited,orderId)])await assert.rejects(read(),{code:'permission-denied'});});
test('S14 private Notes require independent purpose authority and one submission creates one immutable revision',async()=>{
  const ordinary=await member({'orders.read':grant('read')});await assert.rejects(governance.noteList(ordinary,orderId),{code:'permission-denied'});
  const raw=(await db.doc('admins/'+staff.uid).get()).data(),caps={...raw.capabilities};
  for(const action of ['notes-read','notes-add','notes-correct','notes-redact','notes-history'])caps['orders.'+action]={dataPurpose:{active:true,purpose:'order-notes',ids:[orderId],dataClasses:['operational-note']}};
  for(const action of ['escalation-read','escalation-create','escalation-review','escalation-resolve'])caps['orders.'+action]={dataPurpose:{active:true,purpose:'order-governance',ids:[orderId],dataClasses:['escalation']}};
  caps['orders.operations-read']={dataPurpose:{active:true,purpose:'order-operations',ids:[orderId],dataClasses:['operational-context']}};caps['orders.issue']=grant('issue');await db.doc('admins/'+staff.uid).update({capabilities:caps});
  const business=(await db.doc('orders/'+orderId).get()).data(),input={operationId:id(),orderId,componentId:'base',expectedVersion:business.version,action:'add',body:'PRIVATE SYNTHETIC NOTE — Payment verified is inert text'};
  const results=await Promise.all([governance.noteChange(staff,input),governance.noteChange(staff,input)]);assert.deepEqual(results[0],results[1]);
  const note=(await governance.noteList(staff,orderId)).records[0];assert.equal(note.state,'ESTABLISHED');assert.equal(note.originalAuthor.staffId,staff.staffId);assert.equal(note.revision,1);
  assert.equal((await db.collection(`orders/${orderId}/operationalNotes/${note.noteId}/revisions`).get()).size,1);assert.deepEqual((await db.doc('orders/'+orderId).get()).data(),business);
  assert.ok(!JSON.stringify((await db.doc('transactionEvidence/'+input.operationId).get()).data()).includes('PRIVATE SYNTHETIC NOTE'));
  assert.equal((await transactions.reconcile(staff,input.operationId)).noteId,note.noteId);
});
test('S14 Note correction race freezes exact revision; original author and source truth remain intact',async()=>{
  const note=(await governance.noteList(staff,orderId)).records[0],order=await transactions.readOrder(staff,orderId),caps=(await db.doc('admins/'+staff.uid).get()).data().capabilities,second=await member(caps);
  const input={orderId,componentId:'base',expectedVersion:order.version,noteId:note.noteId,expectedRevision:1,action:'correct'};
  const results=await Promise.allSettled([governance.noteChange(staff,{...input,operationId:id(),body:'First legitimate correction'}),governance.noteChange(second,{...input,operationId:id(),body:'Second legitimate correction'})]);assert.equal(results.filter(row=>row.status==='fulfilled').length,1);assert.equal(results.find(row=>row.status==='rejected').reason.code,'stale-conflict');
  const current=(await governance.noteList(staff,orderId)).records[0];assert.equal(current.revision,2);assert.equal(current.originalAuthor.staffId,staff.staffId);assert.ok([staff.staffId,second.staffId].includes(current.correctionActor.staffId));
  const history=await governance.noteHistory(staff,orderId,current.noteId);assert.equal(history.records.length,2);assert.ok(history.records[0].body.includes('PRIVATE SYNTHETIC NOTE'));
});
test('S14 controlled redaction hides current and ordinary historical body without erasing protected evidence',async()=>{
  const note=(await governance.noteList(staff,orderId)).records[0],order=await transactions.readOrder(staff,orderId);
  await governance.noteChange(staff,{operationId:id(),orderId,componentId:'base',expectedVersion:order.version,noteId:note.noteId,expectedRevision:note.revision,action:'redact',reason:'Synthetic minimum-necessary privacy correction'});
  const current=(await governance.noteList(staff,orderId)).records[0];assert.equal(current.state,'REDACTED');assert.ok(!Object.hasOwn(current,'body'));
  const history=await governance.noteHistory(staff,orderId,note.noteId);assert.ok(history.records.every(row=>!Object.hasOwn(row,'body')));assert.ok((await db.doc(`orders/${orderId}/operationalNotes/${note.noteId}/revisions/00000001`).get()).data().body);
  await assert.rejects(governance.noteChange(staff,{operationId:id(),orderId,componentId:'base',expectedVersion:order.version,noteId:note.noteId,expectedRevision:current.revision,action:'correct',body:'Cannot unredact casually'}),{code:'stale-conflict'});
});
test('S14 exact Escalation creation converges across Staff; no fuzzy dedupe or hidden existence disclosure',async()=>{
  const order=await transactions.readOrder(staff,orderId),issueId=id();await transactions.operational(staff,{operationId:id(),orderId,componentId:'base',expectedVersion:order.version,expectedEdition:order.currentEdition,action:'issue',issueId,issueKind:'DELAY',reason:'Synthetic source issue',resolved:false});
  const current=await transactions.readOrder(staff,orderId),work=(await db.doc(`orders/${orderId}/work/base`).get()).data(),caps=(await db.doc('admins/'+staff.uid).get()).data().capabilities,second=await member(caps);
  const input={orderId,componentId:'base',expectedVersion:current.version,sourceKind:'work-issue',sourceId:issueId,expectedSourceVersion:work.version,action:'create',reason:'Current workflow requires authorized governance'};
  const results=await Promise.all([governance.escalationChange(staff,{...input,operationId:id()}),governance.escalationChange(second,{...input,operationId:id()})]);assert.equal(results[0].escalationId,results[1].escalationId);
  assert.equal((await db.collection(`orders/${orderId}/escalations`).get()).size,1);
  const unauthorized=await member({'orders.read':grant('read')});await assert.rejects(governance.escalationList(unauthorized,orderId),{code:'permission-denied'});await assert.rejects(governance.escalationChange(unauthorized,{...input,operationId:id()}),{code:'permission-denied'});
});
test('S14 governance resolution is separate from source issue/Attention/assignment and preserves evidence',async()=>{
  const [row]=(await governance.escalationList(staff,orderId)).records,order=(await db.doc('orders/'+orderId).get()).data(),work=(await db.doc(`orders/${orderId}/work/base`).get()).data();
  const review=await governance.escalationChange(staff,{operationId:id(),orderId,componentId:'base',expectedVersion:order.version,escalationId:row.escalationId,expectedRevision:row.revision,expectedSourceVersion:row.source.version,action:'review'});assert.equal(review.escalationState,'UNDER REVIEW');
  const [reviewed]=(await governance.escalationList(staff,orderId)).records;
  const input={operationId:id(),orderId,componentId:'base',expectedVersion:order.version,escalationId:reviewed.escalationId,expectedRevision:reviewed.revision,expectedSourceVersion:reviewed.source.version,action:'resolve',outcome:'Guidance provided; source work remains independently required'};
  const result=await governance.escalationChange(staff,input);assert.equal(result.escalationState,'RESOLVED');assert.deepEqual(result,await governance.escalationChange(staff,input));
  assert.deepEqual((await db.doc('orders/'+orderId).get()).data(),order);assert.deepEqual((await db.doc(`orders/${orderId}/work/base`).get()).data(),work);assert.equal((await governance.escalationList(staff,orderId)).records[0].source.state,'UNRESOLVED');
  await assert.rejects(governance.escalationChange(staff,{...input,operationId:id()}),{code:'stale-conflict'});
});
test('S14 missing financial evidence stays local: Main Order survives without false zero/paid readiness',async()=>{
  const paymentId=id();await db.doc('payments/'+paymentId).set({paymentId,orderId,componentId:'base',version:1,state:'VERIFIED',amountMinor:100,verifiedAmountMinor:100,contributionId:id(),proofReferenceId:'synthetic-proof',verifiedDecisionId:'missing-synthetic-decision'});
  const result=await workspace.read(staff,orderId);assert.equal(result.orderId,orderId);assert.equal(result.financialState,'unavailable');assert.equal(result.totalPaidMinor,null);assert.equal(result.outstandingMinor,null);assert.equal(result.amountDueNowMinor,null);assert.ok(result.edition);
});
test('S14 existing Global Search handoff reauthorizes current work and never indexes private fields or fabricates Attention',async()=>{
  const source=await workspace.summary(staff,orderId),summary=operationalSummary('orders',{...source,id:source.orderId,privateNote:'DO NOT INDEX',proofReferenceId:'PRIVATE PROOF'});
  assert.ok(!JSON.stringify(summary).includes('DO NOT INDEX'));assert.ok(!JSON.stringify(summary).includes('PRIVATE PROOF'));assert.equal(summary.needsAction,false);
  const open=await resolveOperationalOpen(safeContextCapsule(summary),async()=>summary);assert.equal(open.href,`/admin/orders/${orderId}?work=base`);
  const stale=await resolveOperationalOpen(safeContextCapsule(summary),async()=>({...summary,href:`/admin/orders/${orderId}?work=extension-current`}));assert.equal(stale.href,`/admin/orders/${orderId}?work=extension-current`);
});
test('S14 active-work queue preserves completed Base plus live Extension and supports human source references',async()=>{
  const extId=id();await db.doc(`orders/${orderId}/work/${extId}`).set({componentId:extId,version:1,currentEdition:0,fulfilment:'NOT STARTED',delivery:'NOT PREPARED',completed:false,cancelled:false});
  const reference='UDC-S14-'+id();
  await db.doc('orders/'+orderId).update({status:'COMPLETED',currentWork:extId,activeExtensionId:extId,publicReference:reference,assignedStaffId:staff.staffId});
  const result=await workspace.queue(staff,reference);assert.equal(result.records.length,1);assert.equal(result.records[0].status,'COMPLETED');assert.equal(result.records[0].workCompleted,false);assert.equal(result.records[0].currentWork,extId);
});
test('S14 ambiguous restored identity bytes cannot borrow another Order scope or expose nested private content',async()=>{
  const wrongId=id(),raw=(await db.doc('orders/'+orderId).get()).data();await db.doc('orders/'+wrongId).set(raw);
  await db.doc(`orders/${wrongId}/work/base`).set({componentId:'base',version:1,currentEdition:0});
  await db.doc(`orders/${wrongId}/operationalNotes/private`).set({componentId:'base',revision:1,body:'RESTORED PRIVATE CONTENT'});
  await assert.rejects(workspace.read(staff,wrongId),{code:'permission-denied'});await assert.rejects(workspace.summary(staff,wrongId),{code:'permission-denied'});await assert.rejects(governance.noteList(staff,wrongId),{code:'permission-denied'});
  assert.ok(!(await workspace.queue(staff)).records.some(row=>row.orderId===wrongId));
});
test('S14 Delivery Context revision history is immutable; changed context invalidates exact Dispatch readiness without guessing prior provenance',async()=>{
  const targetId=id(),accountId=(await account.context(owner)).accountId,path=db.doc('orders/'+targetId);
  await path.set({_ownerVersion:3,orderId:targetId,accountId,version:1,status:'OPEN',currentWork:'base',assignedStaffId:staff.staffId,activeExtensionId:null,chatId:'order:'+targetId});
  const workPath=db.doc(`orders/${targetId}/work/base`);await workPath.set({componentId:'base',version:1,currentEdition:1,workingVersion:0,businessApproval:{edition:1},customerApproval:{edition:1},paymentEnabled:{edition:1},fulfilment:'READY FOR DELIVERY PREPARATION',delivery:'READY FOR DISPATCH',deliveryContextVersion:1,deliveryContext:{address:'Known legacy current address'},completed:false,cancelled:false,issues:{}});
  await workPath.collection('editions').doc('1').set({number:1,entries:[],totalMinor:0,amountDueNowMinor:0,currency:'NGN',notes:''});
  const memberPath=db.doc('admins/'+staff.uid),raw=(await memberPath.get()).data(),caps={...raw.capabilities};for(const action of ['delivery-context','ready-dispatch','dispatch'])caps['orders.'+action]=grant(action);await memberPath.update({capabilities:caps});
  async function act(action,extra={}){const current=await transactions.readOrder(staff,targetId);return transactions.operational(staff,{operationId:id(),orderId:targetId,componentId:'base',expectedVersion:current.version,expectedEdition:current.currentEdition,action,...extra});}
  await act('delivery-context',{expectedDeliveryVersion:1,deliveryContext:{address:'New authorized context'}});
  assert.equal((await workPath.get()).data().delivery,'NOT PREPARED');
  const original=(await workPath.collection('deliveryContexts').doc('1').get()).data(),second=(await workPath.collection('deliveryContexts').doc('2').get()).data();assert.equal(original.context.address,'Known legacy current address');assert.equal(original.originalActor,null);assert.equal(original.originalTime,null);assert.equal(original.provenance,'known-current-before-update');assert.equal(second.actor.staffId,staff.staffId);
  await act('ready-dispatch');await act('delivery-context',{expectedDeliveryVersion:2,deliveryContext:{address:'Third authorized context'}});
  assert.deepEqual((await workPath.collection('deliveryContexts').doc('2').get()).data(),second);await assert.rejects(act('dispatch',{expectedDeliveryVersion:3}),{code:'dispatch-conflict'});
  await act('ready-dispatch');await act('dispatch',{expectedDeliveryVersion:3});const work=(await workPath.get()).data();assert.equal(work.delivery,'DISPATCHED');assert.equal((await db.doc('dispatchSnapshots/'+work.dispatchId).get()).data().context.address,'Third authorized context');
  await assert.rejects(act('delivery-context',{expectedDeliveryVersion:3,deliveryContext:{address:'Cannot rewrite dispatched history'}}),{code:'stale-delivery-context'});
});
test('S14 pre-existing physical delivery evidence can continue after commercial cancellation without reopening commerce',async()=>{
  const targetId=id(),accountId=(await account.context(owner)).accountId;
  await db.doc('orders/'+targetId).set({_ownerVersion:3,orderId:targetId,accountId,version:1,status:'CANCELLED',currentWork:'base',assignedStaffId:staff.staffId,activeExtensionId:null,chatId:'order:'+targetId});
  const workPath=db.doc(`orders/${targetId}/work/base`);await workPath.set({componentId:'base',version:1,currentEdition:1,fulfilment:'READY FOR DELIVERY PREPARATION',delivery:'DISPATCHED',dispatchId:'existing-synthetic-dispatch',completed:false,cancelled:true,issues:{},providerSequence:10});
  const path=db.doc('admins/'+staff.uid),raw=(await path.get()).data(),caps={...raw.capabilities};for(const action of ['record-provider-event','reconcile-delivery'])caps['orders.'+action]=grant(action);await path.update({capabilities:caps});
  async function act(action,extra={}){const order=(await db.doc('orders/'+targetId).get()).data();return transactions.operational(staff,{operationId:id(),orderId:targetId,componentId:'base',expectedVersion:order.version,expectedEdition:1,action,...extra});}
  const low=id();await act('record-provider-event',{providerEventId:low,providerSequence:1,providerState:'DELIVERED'});await act('reconcile-delivery',{providerEventId:low});assert.equal((await workPath.get()).data().delivery,'DISPATCHED');
  const current=id();await act('record-provider-event',{providerEventId:current,providerSequence:11,providerState:'DELIVERED'});await act('reconcile-delivery',{providerEventId:current});const work=(await workPath.get()).data();assert.equal(work.delivery,'DELIVERED');assert.equal(work.cancelled,true);assert.equal(work.completed,false);assert.equal((await db.doc('orders/'+targetId).get()).data().status,'CANCELLED');
});
