import test, { before, after } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { initializeApp, deleteApp } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore } from 'firebase-admin/firestore';
import sharp from 'sharp';
import { createAccountService } from '../netlify/lib/account-service.js';
import { createPretransactionService } from '../netlify/lib/pretransaction-service.js';
import { createTransactionService } from '../netlify/lib/transaction-service.js';
import { createConversationReviewService } from '../netlify/lib/transaction-conversation-review.js';
import { createMediaService } from '../netlify/lib/media-service.js';
const id=()=>randomUUID(),secret='local-part3-test-secret-not-production',terms={entries:[{label:'Captured piece',quantity:1,unitAmountMinor:100000,productId:'captured-product'}],amountDueNowMinor:100000};
let app,db,auth,account,cluster,transactions,communication,media,a,b,staff,other,orderId,proofBytes;
const blobs=new Map(),store=()=>({set:async(key,bytes)=>blobs.set(key,Buffer.from(bytes)),get:async key=>blobs.get(key),delete:async key=>blobs.delete(key)});
async function person(name){const email=`${name}-${id()}@example.test`;await account.register({email,password:'Part3-Local-Password!',operationId:id()});const user=await auth.getUserByEmail(email);const claims={uid:user.uid,auth_time:Math.floor(Date.now()/1000)};return{claims,context:await account.context(claims)};}
async function member(name){const uid=id(),staffId=id(),actions=['read','save-working','undo-working','establish-edition','business-approve','enable-payment','extension-propose','extension-revise','extension-activate','extension-close','claim','transfer','remove-assignment','start-fulfilment','fulfilment-component','work-complete','delivery-preparation','delivery-context','ready-dispatch','dispatch','record-provider-event','reconcile-delivery','complete','completion-correction','request-cancellation','cancel','issue','enable-review'];const capabilities=Object.fromEntries(actions.map(action=>['orders.'+action,{domainWide:{active:true,purpose:'order-operations'}}]));capabilities['chats.read']={domainWide:{active:true,purpose:'customer-service'}};capabilities['chats.reply']={assignmentDerived:{active:true,purpose:'customer-service'}};await db.doc('admins/'+uid).set({staffId,active:true,functionAsCouturier:true,eligible:true,available:true,capabilities,label:name});await db.doc('staffIdentities/'+staffId).set({staffId,principalUid:uid,active:true});return{uid,staffId,kind:'staff',auth_time:Math.floor(Date.now()/1000)};}
async function grant(claims,capability,purpose,objectId,dataClass){const path=db.doc('admins/'+claims.uid),raw=(await path.get()).data();await path.update({capabilities:{...raw.capabilities,[capability]:dataClass?{dataPurpose:{active:true,purpose,ids:[objectId],dataClasses:[dataClass]}}:{selectedObject:{active:true,purpose,ids:[objectId]}}}});}
async function read(componentId='base'){return transactions.readOrder(a.claims,orderId,componentId);}
async function command(action,extra={},actor=staff,componentId='base'){const current=await read(componentId);return transactions.operational(actor,{orderId,componentId,expectedVersion:current.version,expectedEdition:current.currentEdition,action,operationId:id(),...extra});}
async function commercial(action,actor=staff,extra={},componentId='base'){const current=await read(componentId);const work=(await db.doc(`orders/${orderId}/work/${componentId}`).get()).data();return transactions.commercial(actor,{orderId,componentId,expectedVersion:current.version,expectedEdition:current.currentEdition,expectedWorkingVersion:work.workingVersion,action,operationId:id(),...extra});}
async function preparePay(componentId='base',correctsPaymentId=null){const current=await read(componentId);return transactions.paymentIntent(a.claims,{orderId,componentId,expectedVersion:current.version,expectedEdition:current.currentEdition,amountMinor:100000,operationId:id(),...(correctsPaymentId?{correctsPaymentId}:{})});}
async function submitPay(intent){const staged=await media.stage(a.claims,{operationId:id(),domain:'payment-proof',objectId:intent.paymentId,expectedVersion:1,expectedEpoch:a.context.epoch,contentType:'image/png',base64:proofBytes.toString('base64')});return transactions.paymentSubmit(a.claims,{operationId:id(),paymentId:intent.paymentId,assetId:staged.assetId});}
before(async()=>{process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099';process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8089';process.env.METADATA_SERVER_DETECTION='none';app=initializeApp({projectId:'demo-udc-section12'},'part3-'+id());db=getFirestore(app);auth=getAuth(app);account=createAccountService({db,auth,secret});transactions=createTransactionService(account);communication=createConversationReviewService(transactions);cluster=createPretransactionService(account,{mainOrderOwner:transactions.mainOrderOwner});media=createMediaService(account,cluster,{getPrivateStore:store,ownerContext:async(...args)=>await transactions.mediaContext(...args)||await communication.mediaContext(...args)});a=await person('transaction-a');b=await person('transaction-b');staff=await member('First');other=await member('Second');proofBytes=await sharp({create:{width:8,height:8,channels:3,background:'#bc9a65'}}).png().toBuffer();});
after(async()=>{await db?.terminate();await deleteApp(app);});
test('private operation field allowlists reject actor, lifecycle and evidence authority mass assignment',async()=>{
  await assert.rejects(transactions.catalogueOrder(a.claims,{operationId:id(),items:[],role:'Super Admin'}),{code:'invalid-argument'});
  await assert.rejects(communication.generalChat(a.claims,{operationId:id(),accountId:b.context.accountId}),{code:'invalid-argument'});
  await assert.rejects(communication.send(a.claims,{chatId:'valid-looking',body:'Data',operationId:id(),actor:{kind:'system'}}),{code:'invalid-argument'});
});
test('direct Catalogue intake is separate from Custom Style, stale source/address denies and snapshots remain captured',async()=>{
  const productId=id(),raw={_ownerVersion:2,_version:1,publicVersion:1,status:'published',publishedAt:Date.now(),publicRepresentation:{name:'Direct catalogue piece',price:100,unitLabel:'per set',category:['Fabric'],images:[{url:'https://example.test/public.jpg'}]}};
  await db.doc('products/'+productId).set(raw);
  const input={operationId:id(),items:[{productId,quantity:2,selections:{},expectedPublicVersion:1}]};
  const first=await transactions.catalogueOrder(a.claims,input);assert.deepEqual(first,await transactions.catalogueOrder(a.claims,input));
  const saved=(await db.doc('orders/'+first.orderId).get()).data();assert.equal(saved.sourceType,'catalogue');assert.equal(saved.sourceRequestId,null);assert.equal(saved.originalSnapshot.items[0].unitAmountMinor,10000);
  await db.doc('products/'+productId).update({publicVersion:2,'publicRepresentation.price':200});
  await assert.rejects(transactions.catalogueOrder(a.claims,{...input,operationId:id()}),{code:'product-state-changed'});
  assert.equal((await db.doc('orders/'+first.orderId).get()).data().originalSnapshot.items[0].unitAmountMinor,10000);
  await assert.rejects(transactions.catalogueOrder(a.claims,{...input,operationId:id(),items:[{...input.items[0],expectedPublicVersion:2}],deliveryAddress:{addressId:'foreign-child',expectedVersion:1}}),{code:'address-state-changed'});
});
test('M06/M07 one handoff creates one real Main Order and canonical Chat, captures Profile without mutable alias',async()=>{const request=await cluster.mutateRequest(a.claims,{operationId:id(),expectedEpoch:a.context.epoch,expectedVersion:0,fields:{notes:'Private request',quantity:1}});const input={requestId:request.requestId,expectedVersion:request.version,expectedEpoch:a.context.epoch,operationId:id()};const results=await Promise.all([cluster.handoff(a.claims,input),cluster.handoff(a.claims,input)]);assert.deepEqual(results[0],results[1]);orderId=results[0].orderId;const order=(await db.doc('orders/'+orderId).get()).data();assert.equal(order.currentWork,'base');assert.equal((await db.doc('accountConversations/'+order.chatId).get()).data().orderId,orderId);assert.equal((await read()).currentEdition,0);const original=order.originalSnapshot;await db.doc('customerProfiles/'+a.context.accountId).update({'fields.fullName':'Later current name'});assert.deepEqual((await db.doc('orders/'+orderId).get()).data().originalSnapshot,original);await assert.rejects(transactions.readOrder(b.claims,orderId),{code:'permission-denied'});});
test('M07 working/root/version/Edition separation, stale writes and exact approval binding',async()=>{await commercial('save-working',staff,{terms});let current=await read();assert.equal(current.currentEdition,0);await commercial('establish-edition');current=await read();assert.equal(current.currentEdition,1);const roots=await db.collection(`orders/${orderId}/work/base/entryRoots`).get();assert.equal(roots.size,1);await commercial('business-approve');await commercial('customer-approve',a.claims);const oldApproval=(await read()).customerApproval;const stale=await read();await commercial('save-working',staff,{terms:{...terms,entries:[{...terms.entries[0],rootId:roots.docs[0].id,label:'Changed current expression'}]}});await assert.rejects(transactions.commercial(a.claims,{orderId,expectedVersion:stale.version,expectedEdition:1,action:'customer-approve',operationId:id()}),{code:'stale-conflict'});await commercial('establish-edition');current=await read();assert.equal(current.currentEdition,2);assert.equal(current.customerApproval,null);assert.equal((await db.doc(`orders/${orderId}/work/base/editions/1`).get()).data().entries[0].label,'Captured piece');assert.equal((await db.collection(`orders/${orderId}/work/base/entryRoots`).get()).size,1);assert.equal(oldApproval.edition,1);await assert.rejects(commercial('enable-payment'),{code:'approval-required'});await commercial('business-approve');await commercial('customer-approve',a.claims);const result=await commercial('enable-payment');assert.equal((await read()).paymentEnabled.edition,2);assert.equal((await transactions.reconcile(staff,result.operationId||'absent')).state,'unknown');});
test('M08 submitted and corrected evidence are append-oriented, assignment cannot read proof, verified ledger effect once',async()=>{let intent=await preparePay(),submitted=await submitPay(intent);const payment=await transactions.paymentDetail(a.claims,submitted.paymentId);assert.equal(payment.paymentState,'RECEIPT SUBMITTED');assert.equal((await read()).totalPaidMinor,0);await assert.rejects(transactions.paymentDetail(staff,submitted.paymentId),{code:'permission-denied'});await grant(staff,'payments.verify','payment-evidence',submitted.paymentId,'payment-proof');await transactions.paymentReview(staff,{paymentId:submitted.paymentId,expectedVersion:1,decision:'NEEDS ATTENTION',reason:'Clearer evidence required',operationId:id()});const originalProof=payment.proofReferenceId;intent=await preparePay('base',submitted.paymentId);const corrected=await submitPay(intent);assert.ok((await db.doc('mediaReferences/'+originalProof).get()).exists);await grant(staff,'payments.verify','payment-evidence',corrected.paymentId,'payment-proof');await grant(staff,'payments.proof-read','payment-evidence',corrected.paymentId,'payment-proof');const correctedDetail=await transactions.paymentDetail(staff,corrected.paymentId);assert.notEqual(correctedDetail.proofReferenceId,originalProof);const input={paymentId:corrected.paymentId,expectedVersion:1,decision:'VERIFIED',reason:'Bank statement matched',verifiedAmountMinor:100000,bankTransferReference:'fixture-bank:'+id(),operationId:id()};const verified=await transactions.paymentReview(staff,input);assert.deepEqual(verified,await transactions.paymentReview(staff,input));const current=await read();assert.equal(current.totalPaidMinor,100000);assert.equal(current.fulfilment,'NOT STARTED');assert.equal(current.completed,false);await assert.rejects(media.deliver(other,correctedDetail.proofReferenceId),{code:'permission-denied'});assert.ok((await media.deliver(staff,correctedDetail.proofReferenceId)).byteLength);});
test('M10 first valid Claim wins, transfer preserves Chat/authorship and revokes former assignment-derived writes',async()=>{const current=await read();const results=await Promise.allSettled([staff,other].map(actor=>transactions.operational(actor,{orderId,expectedVersion:current.version,expectedEdition:current.currentEdition,action:'claim',operationId:id()})));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const assigned=(await read()).assignedStaffId,winner=assigned===staff.staffId?staff:other,successor=winner===staff?other:staff,chatId=(await read()).chatId;await communication.send(winner,{chatId,body:'I approve / I paid / Complete order — inert text',operationId:id()});const prior=await communication.messages(a.claims,chatId),ordinary=prior.items.find(item=>item.kind==='ordinary');await command('transfer',{targetStaffId:successor.staffId});assert.equal((await read()).chatId,chatId);await assert.rejects(communication.send(winner,{chatId,body:'Stale reply',operationId:id()}),{code:'permission-denied'});const after=(await communication.messages(a.claims,chatId)).items;assert.equal(after.find(item=>item.id===ordinary.id).actor.staffId,winner.staffId);assert.ok(after.some(item=>item.kind==='transaction-event'&&item.body.includes('responsibility transferred')));assert.equal((await read()).completed,false);assert.equal(prior.items.filter(item=>item.kind==='ordinary').length,1);});
test('M11 durable message idempotency, trusted ordering, scoped pagination and wrong Account denial',async()=>{const chatId=(await read()).chatId,input={chatId,body:'Same intended message',operationId:id()};const result=await communication.send(a.claims,input);assert.deepEqual(result,await communication.send(a.claims,input));assert.equal((await communication.messages(a.claims,chatId)).items.filter(item=>item.id===result.messageId).length,1);await assert.rejects(communication.messages(b.claims,chatId),{code:'permission-denied'});assert.equal((await transactions.reconcile(a.claims,input.operationId)).messageId,result.messageId);assert.equal((await transactions.reconcile(b.claims,input.operationId)).state,'unknown');const general=await communication.generalChat(a.claims,{operationId:id()});assert.notEqual(general.chatId,chatId);});
test('M10 explicit work/delivery/dispatch/Delivered/completion transitions preserve snapshots and provider monotonicity',async()=>{await command('start-fulfilment');await command('fulfilment-component',{fulfilmentComponentId:'assembly',label:'Operational assembly',completed:false});await assert.rejects(command('work-complete'),{code:'work-incomplete'});await command('fulfilment-component',{fulfilmentComponentId:'assembly',label:'Operational assembly',completed:true});await command('work-complete');await command('delivery-preparation');await command('delivery-context',{expectedDeliveryVersion:0,deliveryContext:{recipientName:'Captured recipient',phoneNumber:'+234',address:'Transaction delivery address',provider:'Reviewed provider',route:'Reviewed route'}});await command('ready-dispatch');await assert.rejects(command('dispatch',{expectedDeliveryVersion:0}),{code:'dispatch-conflict'});await command('dispatch',{expectedDeliveryVersion:1});const work=(await db.doc(`orders/${orderId}/work/base`).get()).data(),snapshot=(await db.doc('dispatchSnapshots/'+work.dispatchId).get()).data();await db.doc('customerProfiles/'+a.context.accountId).update({'fields.phoneNumber':'Changed current phone'});assert.equal((await db.doc('dispatchSnapshots/'+work.dispatchId).get()).data().context.phoneNumber,snapshot.context.phoneNumber);const high=id();await command('record-provider-event',{providerEventId:high,providerSequence:10,providerState:'DELIVERED'});assert.equal((await read()).delivery,'DISPATCHED');await command('reconcile-delivery',{providerEventId:high});const low=id();await command('record-provider-event',{providerEventId:low,providerSequence:1,providerState:'IN PROGRESS'});await command('reconcile-delivery',{providerEventId:low});assert.equal((await read()).delivery,'DELIVERED');assert.equal((await read()).completed,false);await command('complete');assert.equal((await read()).completed,true);assert.equal((await read()).reviewEnabled,false);});
test('M09 exact proposal revisions, one active Extension, completed Base remains completed and Chat reactivates',async()=>{let current=await read();const proposal=await transactions.extension(staff,{orderId,expectedVersion:current.version,action:'propose',terms,operationId:id()});current=await read();await transactions.extension(a.claims,{orderId,extensionId:proposal.extensionId,expectedVersion:current.version,expectedRevision:1,action:'accept',operationId:id()});current=await read();const rival=await transactions.extension(staff,{orderId,expectedVersion:current.version,action:'propose',terms,operationId:id()});current=await read();await transactions.extension(a.claims,{orderId,extensionId:rival.extensionId,expectedVersion:current.version,expectedRevision:1,action:'accept',operationId:id()});current=await read();const attempts=await Promise.allSettled([proposal,rival].map(p=>transactions.extension(staff,{orderId,extensionId:p.extensionId,expectedVersion:current.version,expectedRevision:1,action:'activate',operationId:id()})));assert.equal(attempts.filter(r=>r.status==='fulfilled').length,1);current=await read();assert.equal(current.completed,true);assert.equal(current.status,'COMPLETED');assert.notEqual(current.currentWork,'base');assert.equal((await read(current.currentWork)).customerApproval,null);await communication.send(a.claims,{chatId:current.chatId,body:'Same Chat, later related work',operationId:id()});await assert.rejects(communication.submitReview(a.claims,{orderId,expectedVersion:current.version,body:'Too early',customerServiceRating:5,productQualityRating:5,operationId:id()}),{code:'review-ineligible'});await command('request-cancellation',{reason:'Close Extension'},a.claims,current.currentWork);await command('cancel',{reason:'Reviewed Extension cancellation'},staff,current.currentWork);assert.equal((await read()).currentWork,'base');assert.equal((await read()).completed,true);});
test('M12 explicit review gate, provenance/ratings, moderation vs consent, withdrawal and Draft-only handoff',async()=>{await command('enable-review');const current=await read(),input={orderId,expectedVersion:current.version,productId:'captured-product',body:'Real review <script>inert text</script>',customerServiceRating:5,productQualityRating:4,operationId:id()};const review=await communication.submitReview(a.claims,input);assert.deepEqual(review,await communication.submitReview(a.claims,input));await assert.rejects(communication.submitReview(b.claims,{...input,operationId:id()}),{code:'permission-denied'});await grant(staff,'reviews.moderate','moderation',review.reviewId);await grant(staff,'reviews.publish','moderation',review.reviewId);await communication.changeReview(staff,{reviewId:review.reviewId,expectedVersion:1,action:'moderate',decision:'APPROVED',reason:'Reviewed',operationId:id()});await assert.rejects(communication.changeReview(staff,{reviewId:review.reviewId,expectedVersion:2,action:'publish',operationId:id()}),{code:'publication-ineligible'});await communication.changeReview(a.claims,{reviewId:review.reviewId,expectedVersion:2,action:'permission',scope:'publication',allowed:true,operationId:id()});await communication.changeReview(staff,{reviewId:review.reviewId,expectedVersion:3,action:'publish',operationId:id()});const published=(await communication.feed()).records.find(row=>row.id===review.reviewId);assert.ok(published);assert.equal(published.productSnapshot.name,'Changed current expression');assert.equal(published.author,'');assert.equal(published.authorAccountId,undefined);await communication.changeReview(a.claims,{reviewId:review.reviewId,expectedVersion:4,action:'permission',scope:'publication',allowed:false,operationId:id()});assert.equal((await communication.feed()).records.some(row=>row.id===review.reviewId),false);await grant(staff,'reviews.product-draft','moderation',review.reviewId);await assert.rejects(communication.reviewToDraft(staff,{reviewId:review.reviewId,expectedVersion:5,operationId:id()}),{code:'reuse-not-authorized'});await communication.changeReview(a.claims,{reviewId:review.reviewId,expectedVersion:5,action:'permission',scope:'productReuse',allowed:true,operationId:id()});const memberRef=db.doc('admins/'+staff.uid),membership=(await memberRef.get()).data();await memberRef.update({capabilities:{...membership.capabilities,'products.create':{domainWide:{active:true,purpose:'catalogue'}}}});const draft=await communication.reviewToDraft(staff,{reviewId:review.reviewId,expectedVersion:6,operationId:id()});assert.equal((await db.doc('products/'+draft.productId).get()).data().status,'draft');assert.equal((await db.doc('accountReviews/'+review.reviewId).get()).data().productId,'captured-product');});
test('M07-M12 revoked Account and Staff permissions defeat cached state without rewriting prior evidence',async()=>{const before=(await db.doc('orders/'+orderId).get()).data().originalSnapshot;await db.doc('accounts/'+a.context.accountId).update({lifecycle:'RESTRICTED'});await assert.rejects(read(),{code:'account-restricted'});await assert.rejects(communication.messages(a.claims,`order:${orderId}`),{code:'account-restricted'});await db.doc('accounts/'+a.context.accountId).update({lifecycle:'ACTIVE'});await db.doc('admins/'+staff.uid).update({active:false});await assert.rejects(transactions.readOrder(staff,orderId),{code:'permission-denied'});assert.deepEqual((await db.doc('orders/'+orderId).get()).data().originalSnapshot,before);await db.doc('admins/'+staff.uid).update({active:true});});
test('service-only Review regression, separate media permission, withdrawal and qualified system authorship',async()=>{
  const current=await read(),created=await communication.submitReview(a.claims,{orderId,expectedVersion:current.version,body:'Service without a Product tag',customerServiceRating:5,productQualityRating:4,operationId:id()});
  assert.equal((await db.doc('accountReviews/'+created.reviewId).get()).data().productSnapshot,null);
  const image=await media.stage(a.claims,{operationId:id(),domain:'review',objectId:created.reviewId,expectedVersion:1,expectedEpoch:a.context.epoch,contentType:'image/png',base64:proofBytes.toString('base64')});
  const attached=await communication.attachReviewMedia(a.claims,{operationId:id(),reviewId:created.reviewId,expectedVersion:1,assetId:image.assetId});
  const reference=(await db.doc('accountReviews/'+created.reviewId).get()).data().mediaRefs[0];
  assert.ok((await media.deliver(a.claims,reference)).byteLength);await assert.rejects(media.deliver(b.claims,reference),{code:'permission-denied'});
  assert.equal((await db.doc('accountReviews/'+created.reviewId).get()).data().permissions.publication,false);
  await grant(staff,'reviews.moderate','moderation',created.reviewId);await grant(staff,'reviews.publish','moderation',created.reviewId);
  await communication.changeReview(staff,{reviewId:created.reviewId,expectedVersion:attached.version,action:'moderate',decision:'APPROVED',reason:'Context reviewed',operationId:id()});
  await communication.changeReview(a.claims,{reviewId:created.reviewId,expectedVersion:3,action:'permission',scope:'publication',allowed:true,operationId:id()});
  await communication.changeReview(staff,{reviewId:created.reviewId,expectedVersion:4,action:'publish',operationId:id()});
  const publicMedia=createMediaService(account,cluster,{getPrivateStore:store,ownerContext:async(...args)=>await transactions.mediaContext(...args)||await communication.mediaContext(...args),publicContext:communication.publicMedia});
  assert.ok((await publicMedia.deliver(null,reference,{publicOnly:true})).byteLength);
  await communication.changeReview(a.claims,{reviewId:created.reviewId,expectedVersion:5,action:'permission',scope:'publication',allowed:false,operationId:id()});
  await assert.rejects(publicMedia.deliver(null,reference,{publicOnly:true}),{code:'permission-denied'});
  const sourceOperationId=id();await command('enable-review',{operationId:sourceOperationId});
  const result=await communication.appendSystemMessage({chatId:current.chatId,sourceOperationId,body:'Qualified system status'});assert.deepEqual(result,await communication.appendSystemMessage({chatId:current.chatId,sourceOperationId,body:'Qualified system status'}));
  const messages=await communication.messages(a.claims,current.chatId);assert.equal(messages.items.find(row=>row.id===result.messageId).actor.kind,'system');
});
test('finance recomputes verified owner records rather than trusting a corrupted contribution projection',async()=>{
  const contributions=await db.collection('paymentContributions').where('orderId','==',orderId).get();assert.ok(contributions.size);
  await contributions.docs[0].ref.update({amountMinor:999999});assert.equal((await read()).totalPaidMinor,100000);
  const historical=await transactions.historicalEdition(a.claims,orderId,'base',1);assert.equal(historical.viewedEdition,1);assert.equal(historical.currentEdition,2);
});
test('completion correction appends history, no-new-payable Amendment conserves ledger and requires fresh approval',async()=>{
  const before=(await db.doc(`orders/${orderId}/work/base`).get()).data(),original=(await db.doc('orders/'+orderId).get()).data().originalSnapshot;
  await command('completion-correction',{reason:'Correcting an erroneous completion record'});
  assert.ok((await db.doc('transactionEvidence/'+before.completionId).get()).exists);
  await grant(staff,'orders.save-amendment-working','order-operations',orderId);await grant(staff,'orders.establish-amendment','order-operations',orderId);
  // Existing dispatch history is deliberately not unlocked by an Amendment.
  const current=await read(),work=(await db.doc(`orders/${orderId}/work/base`).get()).data();await assert.rejects(transactions.commercial(staff,{orderId,expectedVersion:current.version,expectedEdition:current.currentEdition,expectedWorkingVersion:work.workingVersion,action:'save-amendment-working',terms,operationId:id()}),{code:'amendment-ineligible'});
  assert.deepEqual((await db.doc('orders/'+orderId).get()).data().originalSnapshot,original);assert.equal((await read()).totalPaidMinor,100000);
});
test('legitimate pre-dispatch Amendment creates a new Edition without new payable scope or borrowed approval',async()=>{
  const previousOrder=orderId,request=await cluster.mutateRequest(a.claims,{operationId:id(),expectedEpoch:a.context.epoch,expectedVersion:0,fields:{notes:'Independent amendment fixture'}});
  const created=await cluster.handoff(a.claims,{operationId:id(),requestId:request.requestId,expectedVersion:1,expectedEpoch:a.context.epoch});orderId=created.orderId;
  await commercial('save-working',staff,{terms});await commercial('establish-edition');await commercial('business-approve');await commercial('customer-approve',a.claims);await commercial('enable-payment');
  await grant(staff,'orders.save-amendment-working','order-operations',orderId);await grant(staff,'orders.establish-amendment','order-operations',orderId);
  const old=await read(),corrected={entries:old.edition.entries.map(entry=>({rootId:entry.rootId,label:'Corrected expression',quantity:entry.quantity,unitAmountMinor:entry.unitAmountMinor,productId:entry.productId,options:entry.options})),amountDueNowMinor:old.edition.amountDueNowMinor,notes:'No new charge'};
  await commercial('save-amendment-working',staff,{terms:corrected});await commercial('establish-amendment');const current=await read();assert.equal(current.currentEdition,2);assert.equal(current.edition.amendment,true);assert.equal(current.edition.totalMinor,old.edition.totalMinor);assert.equal(current.customerApproval,null);assert.equal(current.paymentEnabled,null);assert.ok((await db.doc(`orders/${orderId}/work/base/editions/1`).get()).exists);orderId=previousOrder;
});
