import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {initializeApp,deleteApp} from 'firebase-admin/app';
import {getAuth} from 'firebase-admin/auth';
import {getFirestore} from 'firebase-admin/firestore';
import {createAccountService} from '../netlify/lib/account-service.js';
import {createTransactionService} from '../netlify/lib/transaction-service.js';

// Synthetic local fixtures and the owner-approved isolated Chrome profile.
// No real Customer data, production credentials, provider calls or deployment.
process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099';process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8089';process.env.METADATA_SERVER_DETECTION='none';
const origin='http://127.0.0.1:5182',id=()=>randomUUID(),password='Section14-Local-QA-Only!';
const app=initializeApp({projectId:'demo-udc-section12'},'s14-browser-'+id()),db=getFirestore(app),auth=getAuth(app),account=createAccountService({db,auth,secret:'local-section16-qa-only-secret-not-production'}),transactions=createTransactionService(account);
const staffUid=id(),staffId=id(),staffEmail=`s14-staff-${staffUid}@example.test`;
await auth.createUser({uid:staffUid,email:staffEmail,password,emailVerified:true});
const capabilities=Object.fromEntries(['read','save-working','establish-edition','business-approve','claim','transfer','undo-working','issue'].map(action=>['orders.'+action,{domainWide:{active:true,purpose:'order-operations'}}]));
await db.doc('admins/'+staffUid).set({staffId,active:true,functionAsCouturier:true,eligible:true,available:true,capabilities,displayName:'Synthetic Couturier'});await db.doc('staffIdentities/'+staffId).set({staffId,principalUid:staffUid,active:true});
const staff={uid:staffUid,kind:'staff',auth_time:Math.floor(Date.now()/1000)},email=`s14-owner-${id()}@example.test`;
await account.register({email,password,operationId:id()});const user=await auth.getUserByEmail(email),customer={uid:user.uid,auth_time:Math.floor(Date.now()/1000)},productId=id();
await db.doc('products/'+productId).set({_ownerVersion:2,_version:1,publicVersion:1,status:'published',publishedAt:Date.now(),publicRepresentation:{name:'Synthetic Burgundy Aso Oke',price:1000,unitLabel:'per piece',category:['Fabric'],images:[{url:'https://example.test/public-only.jpg'}]}});
const {orderId}=await transactions.catalogueOrder(customer,{operationId:id(),items:[{productId,quantity:1,selections:{},expectedPublicVersion:1}]});
await db.doc('orders/'+orderId).update({publicReference:'UDC-S14-LOCAL'});
async function commercial(action,extra={}){const source=await transactions.readOrder(staff,orderId),work=(await db.doc(`orders/${orderId}/work/base`).get()).data();return transactions.commercial(staff,{orderId,componentId:'base',expectedVersion:source.version,expectedEdition:source.currentEdition,expectedWorkingVersion:work.workingVersion,action,operationId:id(),...extra});}
await commercial('establish-edition');
const {version,currentEdition}=await transactions.readOrder(staff,orderId);await transactions.operational(staff,{orderId,componentId:'base',expectedVersion:version,expectedEdition:currentEdition,action:'claim',operationId:id()});
for(const[action,dataClass]of[['origin-read','order-origin'],['delivery-read','delivery-context'],['operations-read','operational-context']])capabilities['orders.'+action]={dataPurpose:{active:true,purpose:'order-operations',ids:[orderId],dataClasses:[dataClass]}};
for(const action of ['notes-read','notes-add','notes-correct','notes-redact','notes-history'])capabilities['orders.'+action]={dataPurpose:{active:true,purpose:'order-notes',ids:[orderId],dataClasses:['operational-note']}};
for(const action of ['escalation-read','escalation-create','escalation-review','escalation-resolve'])capabilities['orders.'+action]={dataPurpose:{active:true,purpose:'order-governance',ids:[orderId],dataClasses:['escalation']}};
await db.doc('admins/'+staffUid).update({capabilities});await db.doc(`orders/${orderId}/work/base`).update({deliveryContext:{recipientName:'Synthetic Recipient',phoneNumber:'0000000000',address:'SYNTHETIC PRIVATE DELIVERY ADDRESS',provider:'',route:''},deliveryContextVersion:1});
await mkdir('.tools.local/section14-reference/runtime',{recursive:true});
const target=(await(await fetch('http://127.0.0.1:9228/json')).json()).find(tab=>tab.type==='page');assert.ok(target);
const socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject;});let serial=0;const pending=new Map(),exceptions=[],checks=[];
socket.onmessage=({data})=>{const message=JSON.parse(data);if(message.method==='Runtime.exceptionThrown')exceptions.push(message.params.exceptionDetails.exception?.description||message.params.exceptionDetails.text);const call=pending.get(message.id);if(call){pending.delete(message.id);clearTimeout(call.timer);if(message.error)call.reject(Error(message.error.message));else call.resolve(message.result);}};
const send=(method,params={})=>new Promise((resolve,reject)=>{const number=++serial;pending.set(number,{resolve,reject,timer:setTimeout(()=>{pending.delete(number);reject(Error(method+' timed out'));},30000)});socket.send(JSON.stringify({id:number,method,params}));});
async function evaluate(expression){const value=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(value.exceptionDetails)throw Error(value.exceptionDetails.exception?.description||value.exceptionDetails.text);return value.result.value;}
async function until(expression){for(let n=0;n<250;n++){if(await evaluate(expression))return;await new Promise(resolve=>setTimeout(resolve,100));}throw Error('Not reached: '+expression+'\n'+await evaluate('document.body.innerText.slice(0,2500)'));}
async function navigate(path){await evaluate(`history.pushState({},'',${JSON.stringify(path)});dispatchEvent(new PopStateEvent('popstate'));`);}
async function input(selector,value,kind='HTMLInputElement'){await evaluate(`(()=>{const element=document.querySelector(${JSON.stringify(selector)});if(!element)throw Error('Missing input '+${JSON.stringify(selector)});Object.getOwnPropertyDescriptor(${kind}.prototype,'value').set.call(element,${JSON.stringify(value)});element.dispatchEvent(new Event(${JSON.stringify(kind==='HTMLSelectElement'?'change':'input')},{bubbles:true}));})()`);}
async function click(text){await until(`[...document.querySelectorAll('button')].some(button=>button.textContent.trim()===${JSON.stringify(text)}&&button.getClientRects().length&&!button.disabled)`);await evaluate(`(()=>{const button=[...document.querySelectorAll('button')].find(element=>element.textContent.trim()===${JSON.stringify(text)}&&element.getClientRects().length&&!element.disabled);button.focus();button.click();})()`);}
async function capture(name){const data=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(`.tools.local/section14-reference/runtime/${name}.png`,Buffer.from(data.data,'base64'));}
async function reflow(name){for(const width of[320,390,768,1024,1440]){await send('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:width<600});assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth+1'),true,name+' overflow '+width);checks.push({surface:name,width,reflow:true});if(width===320||width===1440)await capture(name+'-'+width);}await evaluate("document.documentElement.style.zoom='2'");assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth+1'),true,name+' 200% CSS zoom');await evaluate("document.documentElement.style.zoom='1'");}
try{
  await send('Page.enable');await send('Runtime.enable');await send('Accessibility.enable');
  await evaluate("import('/src/firebase/auth.js').then(module=>module.auth.currentUser?module.signOutUser():null)").catch(()=>{});
  await send('Page.navigate',{url:origin+'/tests/section11-browser.html?route=/admin'});await until("!!document.getElementById('admin-email')");await input('#admin-email',staffEmail);await input('#admin-password',password);await evaluate("document.querySelector('.admin-access form').requestSubmit()");await until("!!document.querySelector('.admin-layout')");
  await navigate('/admin/search');await until("!!document.querySelector('.admin-search-form input')");await input('.admin-search-form input','UDC-S14-LOCAL');await click('Search or open');await until("document.querySelector('.admin-operational-card')?.innerText.includes('UDC-S14-LOCAL')");await click('Open current context');await until('location.pathname==='+JSON.stringify('/admin/orders/'+orderId));await until("!!document.querySelector('.order-context-anchor')");
  await navigate('/admin/orders');await until("!!document.querySelector('.order-queue-card')");assert.equal(await evaluate("document.body.innerText.includes('UDC-S14-LOCAL')"),true);await reflow('order-queue');
  await navigate('/admin/orders/'+orderId);await until("!!document.querySelector('.order-context-anchor')");await reflow('workspace');assert.deepEqual(await evaluate("[...document.querySelectorAll('.admin-mobile-bottom a,.admin-mobile-bottom button')].map(element=>element.textContent.trim())"),['Home','Attention','Search','Menu']);
  await click('Editions & Changes');await until("document.body.innerText.includes('Bounded Edition Navigator')");await click('View Original Snapshot');await until("document.body.innerText.includes('Captured ')");assert.equal(await evaluate("document.body.innerText.includes('Later Product Now')"),false);
  await click('Edit Working Changes');await until("!!document.querySelector('.order-terms')");await input('.order-terms input','Synthetic revised Aso Oke');
  await evaluate("(()=>{window.s14OriginalFetch=window.fetch.bind(window);window.s14Consequences=0;window.fetch=async(url,options)=>{const response=await window.s14OriginalFetch(url,options);if(String(url).includes('action=staff-commercial')&&options?.method==='POST'){window.s14Consequences++;await response.clone().arrayBuffer();if(window.s14Consequences===1)throw new TypeError('Synthetic lost acknowledgement after commit');}return response;};})()");
  await click('Review Save of Working Changes');await until("!!document.querySelector('dialog[open]')");assert.equal(await evaluate("document.querySelector('dialog[open]').innerText.includes('Edition 1')"),true);await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await until("!document.querySelector('dialog[open]')");assert.equal(await evaluate('window.s14Consequences'),0);
  await click('Review Save of Working Changes');await click('Confirm action');await until("!![...document.querySelectorAll('button')].find(button=>button.textContent==='Check original action outcome')");assert.equal(await evaluate('window.s14Consequences'),1);assert.equal((await db.doc(`orders/${orderId}/work/base`).get()).data().working.entries[0].label,'Synthetic revised Aso Oke');await capture('unknown-result');await click('Check original action outcome');await until("![...document.querySelectorAll('button')].some(button=>button.textContent==='Check original action outcome')");assert.equal(await evaluate('window.s14Consequences'),1);await evaluate('window.fetch=window.s14OriginalFetch');await click('Close unsaved editor');
  await click('Establish new Edition');await click('Confirm action');await until("document.querySelector('.order-context-anchor > div:last-child p')?.textContent.trim()==='2'");assert.equal((await db.doc(`orders/${orderId}/work/base`).get()).data().currentEdition,2);
  await click('Edition 1');await until("document.body.innerText.includes('Historical Edition · Read Only')&&document.body.innerText.includes('Synthetic Burgundy Aso Oke')");await reflow('edition-history');
  await click('Business Approve current Edition');await until("!!document.querySelector('dialog[open]')");const targetBefore=await transactions.readOrder(staff,orderId);await commercial('save-working',{terms:{entries:targetBefore.edition.entries.map(entry=>({...entry,label:'Third exact Edition'})),amountDueNowMinor:targetBefore.edition.amountDueNowMinor}});await commercial('establish-edition');await click('Confirm action');await until("document.body.innerText.includes('changed elsewhere')");assert.equal((await transactions.readOrder(staff,orderId)).businessApproval,null);await click('Check current source');await until("!!document.querySelector('.order-context-anchor')");
  await click('Fulfilment & Delivery');await until("document.body.innerText.includes('SYNTHETIC PRIVATE DELIVERY ADDRESS')");await reflow('fulfilment-delivery');
  const raw=(await db.doc('admins/'+staffUid).get()).data(),reduced={...raw.capabilities};delete reduced['orders.delivery-read'];await db.doc('admins/'+staffUid).update({capabilities:reduced});await until("!document.body.innerText.includes('SYNTHETIC PRIVATE DELIVERY ADDRESS')");assert.ok(!JSON.stringify(await send('Accessibility.getFullAXTree')).includes('SYNTHETIC PRIVATE DELIVERY ADDRESS'));
  await db.doc('admins/'+staffUid).set(raw);await navigate('/admin/orders/'+orderId+'?section=overview');await until("!!document.querySelector('.order-context-anchor')");await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});assert.equal(await evaluate('document.activeElement!==document.body'),true);
  await click('Product / Provenance');await until("document.querySelector('a[href=\"/shop/"+productId+"\"]')?.textContent.includes('Open current')");await db.doc('products/'+productId).update({status:'unpublished',publicRepresentation:null});await click('Recheck current Product');await until("document.body.innerText.includes('Current public Product context is not available')");assert.ok(await evaluate("document.body.innerText.includes('Synthetic Burgundy Aso Oke')"));
  await click('Governance & Notes');await until("!!document.querySelector('.order-governance textarea[name=body]')");await input('.order-governance textarea[name=body]','PRIVATE NATIVE NOTE — no business authority','HTMLTextAreaElement');await click('Review Add Note');await click('Confirm action');await until("document.querySelector('.order-governance').innerText.includes('ESTABLISHED · Revision 1')");assert.equal((await db.collection(`orders/${orderId}/operationalNotes`).get()).size,1);
  await reflow('operational-notes');await click('Correct exact revision');await input('.order-governance form:last-of-type textarea[name=body]','PRIVATE CORRECTED NATIVE NOTE','HTMLTextAreaElement');await click('Review exact correction');await click('Confirm action');await until("document.querySelector('.order-governance').innerText.includes('CORRECTED · Revision 2')");await click('Close unsaved correction');await input('.order-governance textarea[name=reason]','Synthetic privacy reason','HTMLTextAreaElement');await click('Review controlled redaction');await click('Confirm action');await until("document.querySelector('.order-governance').innerText.includes('REDACTED · Revision 3')");assert.equal(await evaluate("document.querySelector('.order-governance .order-entry-list').innerText.includes('PRIVATE CORRECTED NATIVE NOTE')"),false);
  await click('Fulfilment & Delivery');await until("!!document.querySelector('select[name=kind]')");await input('select[name=kind]','DELAY','HTMLSelectElement');await input('textarea[name=reason]','SYNTHETIC GOVERNANCE SOURCE DELAY','HTMLTextAreaElement');await click('Review issue');await click('Confirm action');await until("document.body.innerText.includes('SYNTHETIC GOVERNANCE SOURCE DELAY')");
  await click('Governance & Notes');await until("!!document.querySelector('[aria-label=\"Escalation Governance\"] textarea[name=reason]')");await input('[aria-label="Escalation Governance"] textarea[name=reason]','Authorized guidance required for this exact local source','HTMLTextAreaElement');await click('Review exact Escalation creation');await click('Confirm action');await until("document.querySelector('[aria-label=\"Escalation Governance\"]').innerText.includes('OPEN · Revision 1')");await click('Review exact Escalation');await click('Confirm action');await until("document.querySelector('[aria-label=\"Escalation Governance\"]').innerText.includes('UNDER REVIEW · Revision 2')");await input('[aria-label="Escalation Governance"] textarea[name=reason]','Guidance provided; independent source work remains','HTMLTextAreaElement');await click('Review governance resolution');await click('Confirm action');await until("document.querySelector('[aria-label=\"Escalation Governance\"]').innerText.includes('RESOLVED · Revision 3')");assert.ok(await evaluate("document.querySelector('[aria-label=\"Escalation Governance\"]').innerText.includes('Source state remains UNRESOLVED')"));await reflow('escalation');
  await send('Network.enable');await send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await until("!document.querySelector('.order-context-anchor')&&(document.body.innerText.includes('Offline / Connectivity Lost')||document.body.innerText.includes('Connection problem'))");assert.ok(!JSON.stringify(await send('Accessibility.getFullAXTree')).includes('SYNTHETIC GOVERNANCE SOURCE DELAY'));await send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});await evaluate("document.querySelector('button')?.textContent==='Check again'&&document.querySelector('button').click()");await until("!!document.querySelector('.order-context-anchor')");
  await evaluate("window.dispatchEvent(new Event('udc:account:authority-uncertain'))");await until("!document.querySelector('.order-context-anchor')");assert.ok(!JSON.stringify(await send('Accessibility.getFullAXTree')).includes('Third exact Edition'));
  await click('Check current source');await until("!!document.querySelector('.order-context-anchor')");await db.doc('admins/'+staffUid).update({active:false});await until("!document.querySelector('.admin-layout')");assert.ok(!JSON.stringify(await send('Accessibility.getFullAXTree')).includes('Third exact Edition'));
  assert.deepEqual(exceptions,[]);await writeFile('.tools.local/section14-reference/runtime/browser-result.json',JSON.stringify({passed:true,checks,nativeStaffSignin:true,realOwnerSaveAndEstablishment:true,ackLossOneConsequence:true,originalOperationReread:true,staleApprovalDidNotRetarget:true,historicalEditionReadOnly:true,exactTargetDialog:true,escapeNoConsequence:true,privateDomAndAXWithdrawal:true,mobileFourTabs:true,keyboard:true,reducedMotion:true,cssZoom200:true,exceptions,productionTested:false},null,2));console.log('Section14 native local Order queue/workspace checks passed.');
}finally{socket.close();await db.terminate();await deleteApp(app);}
