import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import { initializeApp, deleteApp } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore } from 'firebase-admin/firestore';
import { createAccountService } from '../netlify/lib/account-service.js';
import { createTransactionService } from '../netlify/lib/transaction-service.js';
import { createPretransactionService } from '../netlify/lib/pretransaction-service.js';
import { createConfigurationService } from '../netlify/lib/shared-configuration.js';
import { createSystemMaintenance } from '../netlify/lib/system-maintenance.js';
import { defaultCommunicationCopy } from '../netlify/lib/communication-contract.js';

// Owner-approved isolated headless Chrome only. No production credentials,
// provider Email adapter, existing browser profile or production project.
process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099';process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8089';process.env.METADATA_SERVER_DETECTION='none';
const origin='http://127.0.0.1:5182',id=()=>randomUUID(),policy={leaseMs:1000,maxAttempts:2};
const app=initializeApp({projectId:'demo-udc-section12'},'s15-browser-'+id()),db=getFirestore(app),auth=getAuth(app),account=createAccountService({db,auth,secret:'local-section16-qa-only-secret-not-production'}),config=createConfigurationService(account),transactions=createTransactionService(account),requests=createPretransactionService(account,{mainOrderOwner:transactions.mainOrderOwner}),system=createSystemMaintenance(account,{origin});
const password='Section15-Local-QA-Only!',staffUid=id(),staffId=id(),staffEmail=`s15-browser-staff-${staffUid}@example.test`;
await auth.createUser({uid:staffUid,email:staffEmail,password,emailVerified:true});
const capabilities=Object.fromEntries(['read','save-working','establish-edition','business-approve','claim'].map(action=>[`orders.${action}`,{domainWide:{active:true,purpose:'order-operations'}}]));
Object.assign(capabilities,{'notifications.read':{selectedObject:{active:true,purpose:'personal-notifications',ids:[staffId]}},'notifications.edit':{selectedObject:{active:true,purpose:'personal-notifications',ids:[staffId]}},'settings.templates.read':{domainWide:{active:true,purpose:'communication-settings'}},'settings.templates.edit':{domainWide:{active:true,purpose:'communication-settings'}}});
await db.doc(`admins/${staffUid}`).set({staffId,active:true,functionAsCouturier:true,eligible:true,available:true,displayName:'Sample Couturier',capabilities});await db.doc(`staffIdentities/${staffId}`).set({staffId,principalUid:staffUid,active:true});
const staff={uid:staffUid,kind:'staff',auth_time:Math.floor(Date.now()/1000)};
async function seedCustomer(){const email=`s15-browser-${id()}@example.test`;await account.register({email,password,operationId:id()});const user=await auth.getUserByEmail(email);await auth.updateUser(user.uid,{emailVerified:true});const claims={uid:user.uid,auth_time:Math.floor(Date.now()/1000)},context=await account.context(claims);return{email,claims,context};}
const a=await seedCustomer(),b=await seedCustomer();
async function publish(templateId){const current=await config.read(staff,templateId),draft=await config.mutate(staff,{configurationId:templateId,expectedVersion:current.version,action:'draft',value:defaultCommunicationCopy(templateId),operationId:id()});const operationId=id();await config.mutate(staff,{configurationId:templateId,expectedVersion:draft.version,proposedVersion:draft.proposedVersion,action:'activate',operationId});await system.processEvent(account.keyed(`event:configuration:${operationId}`),policy);}
await publish('template:s15:customer:action');await publish('template:s15:customer:information');await publish('template:s15:staff:information');
const request=await requests.mutateRequest(a.claims,{expectedEpoch:1,expectedVersion:0,operationId:id(),fields:{notes:'Synthetic Section15 browser source'}}),handoff=await requests.handoff(a.claims,{requestId:request.requestId,expectedVersion:1,expectedEpoch:1,operationId:id()}),orderId=handoff.orderId;
await db.doc(`orders/${orderId}`).update({publicReference:'UDC-SAMPLE-1047'});
async function commercial(action,extra={}){const order=await transactions.readOrder(staff,orderId),work=(await db.doc(`orders/${orderId}/work/base`).get()).data(),operationId=id();await transactions.commercial(staff,{orderId,componentId:'base',action,expectedVersion:order.version,expectedEdition:order.currentEdition,expectedWorkingVersion:work.workingVersion,operationId,...extra});return operationId;}
await commercial('save-working',{terms:{entries:[{label:'Synthetic Aso Oke order',quantity:1,unitAmountMinor:100000}],amountDueNowMinor:30000}});await commercial('establish-edition');const approved=await commercial('business-approve');await system.processEvent(account.keyed(`event:transaction:${approved}`),policy);
const order=await transactions.readOrder(staff,orderId),claimId=id();await transactions.operational(staff,{orderId,componentId:'base',action:'claim',expectedVersion:order.version,expectedEdition:order.currentEdition,operationId:claimId});await system.processEvent(account.keyed(`event:transaction:${claimId}`),policy);
const staffEmailBranches=await db.collection('notificationBindings').where('recipientKey','==',`staff:${staffId}`).where('channel','==','email').get(),deliveryIds=staffEmailBranches.docs.map(row=>row.id);
Object.assign(capabilities,{'communications.delivery.read':{dataPurpose:{active:true,purpose:'communication-reliability',ids:deliveryIds,dataClasses:['delivery-evidence']}},'communications.delivery.edit':{dataPurpose:{active:true,purpose:'communication-reliability',ids:deliveryIds,dataClasses:['delivery-evidence']}}});await db.doc(`admins/${staffUid}`).update({capabilities});

const target=(await(await fetch('http://127.0.0.1:9228/json')).json()).find(tab=>tab.type==='page');assert.ok(target);const socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject;});let serial=0;const pending=new Map(),errors=[];
socket.onmessage=({data})=>{const message=JSON.parse(data);if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails.exception?.description||message.params.exceptionDetails.text);const request=pending.get(message.id);if(request){pending.delete(message.id);clearTimeout(request.timer);if(message.error)request.reject(Error(message.error.message));else request.resolve(message.result);}};
const send=(method,params={})=>new Promise((resolve,reject)=>{const requestId=++serial;pending.set(requestId,{resolve,reject,timer:setTimeout(()=>reject(Error(method+' timed out')),30000)});socket.send(JSON.stringify({id:requestId,method,params}));});
async function evaluate(expression){const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result.value;}
async function until(expression){for(let n=0;n<250;n++){if(await evaluate(expression))return;await new Promise(resolve=>setTimeout(resolve,100));}throw Error('Not reached: '+expression+'\n'+await evaluate('document.body.innerText.slice(0,2000)'));}
async function navigate(path){await evaluate(`history.pushState({},'',${JSON.stringify(path)});dispatchEvent(new PopStateEvent('popstate'));`);}
async function input(selector,value,textarea=false){await evaluate(`(()=>{const element=document.querySelector(${JSON.stringify(selector)});if(!element)throw Error('Missing input');Object.getOwnPropertyDescriptor(${textarea?'HTMLTextAreaElement':'HTMLInputElement'}.prototype,'value').set.call(element,${JSON.stringify(value)});element.dispatchEvent(new Event('input',{bubbles:true}));})()`);}
async function click(label,container='document'){await until(`[...${container}.querySelectorAll('button')].some(button=>(button.querySelector('[data-filter-label]')?.textContent||button.textContent).trim()===${JSON.stringify(label)}&&button.getClientRects().length&&!button.disabled)`);await evaluate(`(()=>{const element=[...${container}.querySelectorAll('button')].find(button=>(button.querySelector('[data-filter-label]')?.textContent||button.textContent).trim()===${JSON.stringify(label)}&&button.getClientRects().length&&!button.disabled);if(!element)throw Error('Missing ready button '+${JSON.stringify(label)});element.click();})()`);}
async function screenshot(name){const capture=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(`.tools.local/section15-part1-reference/runtime-${name}.png`,Buffer.from(capture.data,'base64'));}
const widths=[320,390,768,1024,1440],checks=[];
async function reflow(name){for(const width of widths){await send('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:width<600});assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth+1'),true,`${name} overflow at ${width}`);checks.push({name,width,reflow:true});if(width===320||width===1440)await screenshot(`${name}-${width}`);}await evaluate("document.documentElement.style.zoom='2'");assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth+1'),true,`${name} 200% reflow`);await evaluate("document.documentElement.style.zoom='1'");}
try{
  await send('Page.enable');await send('Runtime.enable');await send('Accessibility.enable');await send('Page.navigate',{url:origin+'/tests/section11-browser.html?route=/signin'});await until("!!document.getElementById('auth-email')");await input('#auth-email',a.email);await input('#auth-password',password);await evaluate("document.querySelector('.auth-flow__form').requestSubmit()");await until("location.pathname==='/profile'");await navigate('/notifications');await until("document.querySelector('.notification-centre .notification-group')?.innerText.includes('UDC-SAMPLE-1047')");
  assert.deepEqual(await evaluate("[...document.querySelectorAll('[data-filter-label]')].map(label=>label.textContent.trim())"),['All','Unread','Action Required']);
  await until("!!document.querySelector('.notification-group')");assert.ok(await evaluate("document.querySelector('.notification-group').innerText.includes('2 loaded updates')"));await evaluate("document.querySelector('.notification-group > details > summary').click()");
  await reflow('customer-centre');
  await click('Action Required');await until("document.querySelectorAll('.notification-list .notification-item').length===1");await evaluate("document.querySelector('.notification-item summary').click()");await click('Archive');await until("!![...document.querySelectorAll('button')].find(button=>button.textContent==='Undo')");await click('Undo');await until("document.querySelectorAll('.notification-list .notification-item').length===1");assert.equal((await db.doc(`orders/${orderId}/work/base`).get()).data().customerApproval,null);
  await evaluate("(()=>{const original=window.fetch;window.s15ReadAttempts=0;window.fetch=async(url,options)=>{if(String(url).includes('action=notification-change')&&options?.method==='POST'){window.s15ReadAttempts++;const response=await original(url,options);await response.clone().arrayBuffer();if(window.s15ReadAttempts===1)throw new TypeError('Synthetic acknowledgement loss');return response;}return original(url,options);};})()");await evaluate("document.querySelector('.notification-item summary').click()");await click('Mark read');await until("document.body.innerText.includes('An earlier action is being checked')");await screenshot('customer-unknown-result');assert.equal(await evaluate('window.s15ReadAttempts'),1);await click('Check outcome');await until("!document.body.innerText.includes('An earlier action is being checked')");assert.equal(await evaluate('window.s15ReadAttempts'),1);
  await click('All');await until("document.querySelectorAll('.notification-list .notification-item').length===2");await click('Mark all read');await until("[...document.querySelectorAll('.notification-read-state')].every(element=>element.textContent==='Read')");
  await send('Emulation.setDeviceMetricsOverride',{width:320,height:900,deviceScaleFactor:1,mobile:true});await evaluate("[...document.querySelectorAll('.notification-bell')].find(button=>button.getClientRects().length).click()");await until("!!document.querySelector('.notification-drawer[open] .notification-item')");await evaluate("document.querySelector('.notification-drawer[open] .notification-group > details > summary')?.click()");assert.deepEqual(await evaluate("(()=>{const r=document.querySelector('.notification-drawer[open]').getBoundingClientRect();return{width:Math.round(r.width),height:Math.round(r.height),top:Math.round(r.top),left:Math.round(r.left)};})()"),{width:320,height:900,top:0,left:0});await screenshot('customer-latest-320');
  await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await until("!document.querySelector('.notification-drawer[open]')");await until("document.activeElement.classList.contains('notification-bell')");
  await evaluate("import('/src/firebase/auth.js').then(module=>module.signOutUser())");await navigate('/signin');await until("!!document.getElementById('auth-email')");await input('#auth-email',b.email);await input('#auth-password',password);await evaluate("document.querySelector('.auth-flow__form').requestSubmit()");await until("location.pathname==='/profile'||document.body.innerText.includes('You’re already signed in')");assert.equal(await evaluate("import('/src/firebase/auth.js').then(module=>module.auth.currentUser?.uid)"),b.claims.uid);if(await evaluate("location.pathname==='/signin'"))await click('CONTINUE →');await until("location.pathname==='/profile'");await navigate('/notifications');await until("document.body.innerText.includes('No notifications in this view')");assert.equal(await evaluate("document.body.innerText.includes('UDC-SAMPLE-1047')"),false);
  await evaluate("import('/src/firebase/auth.js').then(module=>module.signOutUser())");await send('Page.navigate',{url:origin+'/tests/section11-browser.html?route=/admin'});await until("!!document.getElementById('admin-email')");await input('#admin-email',staffEmail);await input('#admin-password',password);await evaluate("document.querySelector('.admin-access form').requestSubmit()");await until("!!document.querySelector('.admin-layout')");await navigate('/admin/notifications');await until("!!document.querySelector('.notification-centre .notification-item')");assert.deepEqual(await evaluate("[...document.querySelectorAll('[data-filter-label]')].map(label=>label.textContent.trim())"),['All','Unread','Security']);assert.deepEqual(await evaluate("[...document.querySelectorAll('.admin-mobile-bottom a,.admin-mobile-bottom button')].map(element=>element.textContent.trim())"),['Home','Attention','Search','Menu']);await reflow('staff-centre');
  await navigate('/admin/notifications/templates');await until("document.querySelectorAll('.communication-template-card').length===9");await click('Open Template',"document.querySelector('.communication-template-card')");await until("!!document.querySelector('.communication-editor')");await input('.communication-editor input','A synthetic future subject');await click('Save Draft');await until("document.querySelector('.communication-fixed-context')?.innerText.includes('Draft:')&&!document.querySelector('.communication-editor button[type=submit]').disabled");await click('Preview');await until("!!document.querySelector('.communication-preview')");assert.ok(await evaluate("document.querySelector('.communication-preview').innerText.includes('Synthetic')"));await click('Publish saved Draft');await until("document.querySelector('.communication-fixed-context')?.innerText.includes('Draft: None')");await click('Version history');await until("!!document.querySelector('[aria-label=\"Template version history\"]')");await reflow('template-editor');await click('Send internal TEST');await until("document.body.innerText.includes('No test message was sent')");
  const raw=(await db.doc(`admins/${staffUid}`).get()).data(),remaining={...raw.capabilities};delete remaining['settings.templates.read'];delete remaining['settings.templates.edit'];await db.doc(`admins/${staffUid}`).update({capabilities:remaining});await until("!document.querySelector('.communication-editor')");assert.equal(await evaluate("document.body.innerText.includes('A synthetic future subject')"),false);await db.doc(`admins/${staffUid}`).set(raw);
  await navigate('/admin/notifications/delivery-issues');await until("document.body.innerText.includes('Communication route unavailable')");await click('View issue');await until("!!document.querySelector('[aria-label=\"Delivery Issue detail\"]')");assert.equal(await evaluate("[...document.querySelectorAll('button')].find(button=>button.textContent==='Safe Retry').disabled"),true);await click('Recheck status');await until("document.body.innerText.includes('Delivery outcome remains uncertain')");await reflow('delivery-issues');
  await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});const focused=await evaluate("(()=>{const s=getComputedStyle(document.activeElement);return{outlineWidth:s.outlineWidth,outlineStyle:s.outlineStyle};})()");assert.notEqual(focused.outlineStyle,'none');
  const accessibility=await send('Accessibility.getFullAXTree');assert.ok(accessibility.nodes.some(node=>node.role?.value==='heading'&&node.name?.value==='Delivery Issues'));
  assert.ok(await evaluate("(parseFloat(getComputedStyle(document.querySelector('.notification-bell')).transitionDuration)||0)<=0.01"));
  await db.doc(`admins/${staffUid}`).update({active:false});await until("!document.querySelector('.admin-layout')");assert.equal(await evaluate("document.body.innerText.includes('Communication route unavailable')"),false);const inactiveAX=await send('Accessibility.getFullAXTree');assert.equal(inactiveAX.nodes.some(node=>node.name?.value==='Delivery Issue detail'),false);await screenshot('staff-inactive');
  assert.deepEqual(errors,[]);await writeFile('.tools.local/section15-part1-reference/browser-result.json',JSON.stringify({checks,customerFilters:true,staffFilters:true,sameSessionUndo:true,readDidNotApproveSource:true,principalIsolation:true,mobileLatestFullScreen:true,escapeFocusRestoration:true,templateDraftPreviewPublish:true,templateRevocationShield:true,testSendNoProviderNoEmail:true,mobileStaffFourTabs:true,keyboardFocus:focused,accessibilityTree:true,productionTested:false},null,2));console.log('Section15 isolated native Customer/Staff notification and Template browser checks passed.');
}finally{socket.close();await db.terminate();await deleteApp(app);}
