import { useCallback, useEffect, useState } from 'react';
import { NavLink, useNavigate } from 'react-router-dom';
import NotificationCentre from '../../../components/notifications/NotificationCentre';
import { useStaff } from '../../../context/StaffContext';
import { useAuth } from '../../../context/AuthContext';
import { allows, authorizationRoutes, staffFingerprint } from '../../../services/staffAuthorization';
import { accountRequest } from '../../../services/accountApi';
import { usePrincipalFence } from '../../../hooks/usePrincipalFence';
import { ownerErrorCopy, readOperationMarker, writeOperationMarker, clearOperationMarker } from '../../../services/ownerOperation';
import Button from '../../../components/common/Button';
import SourceStatus from '../../../components/common/SourceStatus';
import '../../../components/notifications/Notifications.css';

function LocalNavigation() {
  const {staff}=useStaff();
  const template=authorizationRoutes(staff,'settings.templates.read','communication-settings').length>0;
  const delivery=authorizationRoutes(staff,'communications.delivery.read','communication-reliability').some(route=>route.family==='dataPurpose');
  return <nav className="communication-nav" aria-label="Notifications management"><NavLink end to="/admin/notifications">Notifications</NavLink>{template&&<NavLink to="/admin/notifications/templates">Templates</NavLink>}{delivery&&<NavLink to="/admin/notifications/delivery-issues">Delivery Issues</NavLink>}</nav>;
}
export default function StaffNotifications(){return <><LocalNavigation/><NotificationCentre domain="staff"/></>;}

export function Templates() {
  const {staff}=useStaff(),{user}=useAuth();
  const scope=`${user?.uid}:templates:${staffFingerprint(staff)}`,markerKey=`udc:template:${user?.uid}`;
  const [library,setLibrary]=useState(null),[selected,setSelected]=useState(null),[record,setRecord]=useState(null),[copy,setCopy]=useState(null),[preview,setPreview]=useState(null),[preset,setPreset]=useState('standard'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState(null);
  const fence=usePrincipalFence(scope,()=>{setLibrary(null);setSelected(null);setRecord(null);setCopy(null);setPreview(null);});
  const [history,setHistory]=useState(null);
  const [previewMode,setPreviewMode]=useState('in-app');
  const load=useCallback(async()=>{const ticket=fence.begin();try{const result=await accountRequest('staff-template-library');if(fence.current(ticket))setLibrary({scope,records:result.records});}catch(failure){if(fence.current(ticket))setError(ownerErrorCopy(failure,'Templates'));}},[fence,scope]);
  useEffect(()=>{load();setPending(readOperationMarker(markerKey));},[load,markerKey]);
  async function select(definition){const ticket=fence.begin();setBusy(true);setError('');setRecord(null);setCopy(null);setPreview(null);try{const result=await accountRequest('staff-configuration',{configurationId:definition.id});if(fence.current(ticket)){setSelected({...definition,scope});setRecord(result);setCopy(result.draft||result.effective?.value||definition.defaultCopy);}}catch(failure){if(fence.current(ticket))setError(ownerErrorCopy(failure));}finally{if(fence.current(ticket))setBusy(false);}}
  async function mutate(action){if(!selected||!record||pending)return;const ticket=fence.begin(),operationId=crypto.randomUUID();setBusy(true);setError('');try{writeOperationMarker(markerKey,{operationId});setPending({operationId});await accountRequest('staff-configuration-mutate',{configurationId:selected.id,expectedVersion:record.version,operationId,action,...(action==='draft'?{value:copy}:{proposedVersion:record.proposedVersion})});if(fence.current(ticket)){clearOperationMarker(markerKey);setPending(null);await select(selected);await load();}}catch(failure){if(fence.current(ticket)){setError(failure.code?.startsWith('template-')||failure.code==='unsafe-template-copy'?'Check the allowed variables, required reference and controlled CTA. Protected Security wording cannot be changed.':ownerErrorCopy(failure,'This template change'));if(failure.code!=='auth/outcome-unknown'){clearOperationMarker(markerKey);setPending(null);}}}finally{if(fence.current(ticket))setBusy(false);}}
  async function check(){const operation=pending||readOperationMarker(markerKey);if(!operation)return;const ticket=fence.begin();setBusy(true);try{const result=await accountRequest(operation.phase==='test'?'staff-template-test-result':'configuration-operation',{operationId:operation.operationId});if(!fence.current(ticket))return;if(result.state==='committed'||result.state==='PROVIDER ACCEPTED'){clearOperationMarker(markerKey);setPending(null);if(selected?.scope===scope)await select(selected);await load();if(result.state==='PROVIDER ACCEPTED')setError('The provider accepted the internal TEST message. This is not Customer delivery or read evidence.');}else setError('The earlier action is still unconfirmed. It has not been repeated.');}catch(failure){if(fence.current(ticket))setError(ownerErrorCopy(failure));}finally{if(fence.current(ticket))setBusy(false);}}
  async function showPreview(){const ticket=fence.begin();setBusy(true);setError('');try{const result=await accountRequest('staff-template-preview',{configurationId:selected.id,value:copy,preset});if(fence.current(ticket))setPreview(result);}catch{if(fence.current(ticket))setError('The preview could not be rendered. Check the allowed variables and required reference.');}finally{if(fence.current(ticket))setBusy(false);}}
  async function testSend(){if(!selected||selected.scope!==scope||pending||busy)return;const ticket=fence.begin(),operationId=crypto.randomUUID();setBusy(true);setError('');try{writeOperationMarker(markerKey,{operationId,phase:'test'});setPending({operationId,phase:'test'});const result=await accountRequest('staff-template-test-send',{configurationId:selected.id,value:copy,preset,operationId});if(!fence.current(ticket))return;if(['PROVIDER ACCEPTED','ROUTE UNAVAILABLE'].includes(result.state)){clearOperationMarker(markerKey);setPending(null);setError(result.state==='PROVIDER ACCEPTED'?'The provider accepted the internal TEST message. This is not Customer delivery or read evidence.':'Internal Test Send is unavailable: the trusted Email adapter is not configured. No test message was sent.');}else setError('Internal Test Send outcome is uncertain. Check before sending another test.');}catch(failure){if(fence.current(ticket)){setError(ownerErrorCopy(failure,'Internal Test Send'));if(failure.code!=='auth/outcome-unknown'){clearOperationMarker(markerKey);setPending(null);}}}finally{if(fence.current(ticket))setBusy(false);}}
  async function showHistory(before){if(selected?.scope!==scope)return;const ticket=fence.begin();setBusy(true);try{const result=await accountRequest('staff-template-history',{configurationId:selected.id,...(before?{before}:{})});if(fence.current(ticket))setHistory(prior=>({...result,scope,configurationId:selected.id,records:before&&prior?.configurationId===selected.id?[...prior.records,...result.records]:result.records}));}catch(failure){if(fence.current(ticket))setError(ownerErrorCopy(failure,'Template history'));}finally{if(fence.current(ticket))setBusy(false);}}
  const safeLibrary=library?.scope===scope?library.records:null;
  const canEdit=selected&&allows(staff,'settings.templates.edit',{purpose:'communication-settings',objectId:selected.id,action:'edit'});
  return <section className="notification-centre"><LocalNavigation/><header><p className="eyebrow">Operations / Notifications</p><h1>Communication Templates</h1><p>Controlled Customer and Staff communication. Preview is a simulation, not delivery.</p></header>
    {error&&<SourceStatus state="unavailable">{error}</SourceStatus>}{!safeLibrary&&!error&&<SourceStatus state="checking">Checking current Template access.</SourceStatus>}{safeLibrary?.length===0&&<SourceStatus state="restricted">Template management is not available with your current access.</SourceStatus>}
    {!selected&&<div className="communication-library">{safeLibrary?.map(definition=><article className="communication-template-card" key={definition.id}><h2>{definition.domain==='staff'?'Staff':'Customer'} · {definition.taxonomy}</h2><p>{definition.heading}</p><p>{definition.channels.join(' + ')} · {definition.effectiveVersion?`Published Current v${definition.effectiveVersion}`:'No Published version'}{definition.proposedVersion?` · Draft v${definition.proposedVersion}`:''}</p><Button variant="secondary" disabled={busy} onClick={()=>select(definition)}>Open Template</Button></article>)}</div>}
    {selected?.scope===scope&&copy&&record&&<>
      <Button variant="ghost" onClick={()=>{setSelected(null);setCopy(null);setPreview(null);}}>Back to library</Button>
      <div className="communication-fixed-context"><h2>{selected.heading}</h2><p>{selected.domain} · {selected.taxonomy} · {selected.channels.join(' + ')}</p><p>Semantic action: {selected.semanticAction}. Destination is system-resolved.</p><p>Published Current: {record.effective?.effectiveVersion||'None'} · Draft: {record.proposedVersion||'None'}. Security meaning is protected.</p><p>Allowed variables: {selected.allowedVariables.map(name=>`{{${name}}}`).join(', ')}</p></div>
      <form className="communication-editor" onSubmit={event=>{event.preventDefault();mutate('draft');}}>
        {Object.entries({subject:'Email subject',preheader:'Preheader',heading:'Event heading',body:'Body',support:'Support block'}).map(([field,label])=><label key={field}>{label}{field==='body'?<textarea rows={6} value={copy[field]} disabled={!canEdit||busy||Boolean(pending)||selected.securityLocked} onChange={event=>{setCopy({...copy,[field]:event.target.value});setPreview(null);}}/>:<input value={copy[field]} maxLength={field==='heading'?120:field==='support'?200:150} disabled={!canEdit||busy||Boolean(pending)||selected.securityLocked&&field==='heading'} onChange={event=>{setCopy({...copy,[field]:event.target.value});setPreview(null);}}/>}</label>)}
        <label>Controlled CTA label<select value={copy.ctaLabel} disabled={!canEdit||busy||Boolean(pending)} onChange={event=>setCopy({...copy,ctaLabel:event.target.value})}>{selected.ctaLabels.map(label=><option key={label}>{label}</option>)}</select></label>
        <div className="notification-filters"><Button type="submit" disabled={!canEdit||busy||Boolean(pending)}>Save Draft</Button><Button type="button" variant="secondary" disabled={busy||Boolean(pending)} onClick={showPreview}>Preview</Button><Button type="button" disabled={!canEdit||busy||Boolean(pending)||!record.proposedVersion} onClick={()=>mutate('activate')}>Publish saved Draft</Button></div>
      </form>
      <label>Synthetic preview persona<select value={preset} onChange={event=>{setPreset(event.target.value);setPreview(null);}}><option value="standard">Sample Customer / Staff</option><option value="no-name">No display name</option><option value="long">Long reference and name</option></select></label>
      <label>Preview mode<select value={previewMode} onChange={event=>setPreviewMode(event.target.value)}><option value="in-app">In-App</option><option value="email-desktop">Email — desktop</option><option value="email-mobile">Email — mobile / images blocked</option><option value="external">External / lock-screen preview</option><option value="plain-text">Plain-text fallback</option></select></label>
      {preview&&<article className={`communication-preview communication-preview--${previewMode}`} aria-label="Synthetic communication preview"><p>PREVIEW · Synthetic sample data · Not sent</p><p>UNIVERSAL DICTA COUTURE</p><p>Subject: {preview.subject}</p><p>Preheader: {preview.preheader}</p>{previewMode!=='external'&&<><p>{preview.greeting}</p><h2>{preview.heading}</h2><p>{preview.body}</p><p>{preview.ctaLabel} · System-resolved destination</p><p>{preview.support}</p></>}</article>}
      <p>Internal Test Send uses synthetic data and your verified Staff destination only. It creates no Customer notification or transaction history.</p><Button variant="secondary" onClick={testSend} disabled={!canEdit||busy||Boolean(pending)}>Send internal TEST</Button>
      <Button variant="ghost" onClick={()=>showHistory()} disabled={busy}>Version history</Button>
      {history?.scope===scope&&history.configurationId===selected.id&&<section aria-label="Template version history"><h2>Version history</h2>{history.partial&&<p>Older history is partially available. No source evidence has been removed.</p>}{history.records.map(version=><article className="communication-template-card" key={version.version}><h3>v{version.version} · {version.state}</h3><p>{version.value.heading}</p><p>{new Date(version.createdAt).toLocaleString('en-NG')}</p></article>)}{history.next&&<Button variant="secondary" disabled={busy} onClick={()=>showHistory(history.next)}>Load older versions</Button>}</section>}
    </>}
    {pending&&<SourceStatus state="unknown-result">Save or publish outcome needs checking.<Button variant="secondary" onClick={check} disabled={busy}>Check outcome</Button></SourceStatus>}
  </section>;
}

export function DeliveryIssues() {
  const {staff}=useStaff(),{user}=useAuth(),scope=`${user?.uid}:delivery:${staffFingerprint(staff)}`;
  const [source,setSource]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [detail,setDetail]=useState(null),[known,setKnown]=useState(null),navigate=useNavigate();
  const fence=usePrincipalFence(scope,()=>setSource(null));
  const load=useCallback(async()=>{const ticket=fence.begin();try{const result=await accountRequest('staff-delivery-issues');if(fence.current(ticket))setSource({scope,...result});}catch(failure){if(fence.current(ticket))setError(ownerErrorCopy(failure,'Delivery Issues'));}},[fence,scope]);
  useEffect(()=>{load();},[load]);
  async function recheck(branchId,action='recheck'){const ticket=fence.begin();setBusy(true);setKnown(null);try{const result=await accountRequest('staff-delivery-recover',{branchId,action});if(fence.current(ticket)){if(result.route){navigate(result.route);return;}setKnown({scope,branchId,state:result.state});await load();setError(result.state==='unknown'||result.state==='OUTCOME UNCERTAIN'?'Delivery outcome remains uncertain. No message has been repeated.':result.state==='not-applied'?'The provider confirms that the effect was not applied. Any safe retry will recheck current eligibility.':'Delivery evidence was checked. Provider acceptance is not Customer read or inbox placement.');}}catch(failure){if(fence.current(ticket))setError(ownerErrorCopy(failure));}finally{if(fence.current(ticket))setBusy(false);}}
  async function openDetail(branchId){const ticket=fence.begin();setBusy(true);setDetail(null);setKnown(null);try{const result=await accountRequest('staff-delivery-issue',{branchId});if(fence.current(ticket))setDetail({scope,...result});}catch(failure){if(fence.current(ticket))setError(ownerErrorCopy(failure,'Delivery evidence'));}finally{if(fence.current(ticket))setBusy(false);}}
  const records=source?.scope===scope?source.records:null;
  return <section className="notification-centre"><LocalNavigation/><h1>Delivery Issues</h1><p>Communication reliability evidence. This is separate from personal Notifications and Attention.</p>{error&&<SourceStatus state="unavailable">{error}</SourceStatus>}{!records&&!error&&<SourceStatus state="checking">Checking current delivery-evidence access.</SourceStatus>}{records?.length===0&&<p>No currently accessible Delivery Issues are shown.</p>}<div className="communication-library">{records?.map(issue=><article key={issue.branchId} className="communication-template-card"><h2>{issue.state}</h2><p>{issue.domain} · {issue.channel}</p><p>{issue.reason}</p><p>Human action: {issue.humanActionRequired?'Required':'Not required'}</p><Button variant="secondary" disabled={busy} onClick={()=>openDetail(issue.branchId)}>View issue</Button><Button variant="ghost" disabled={busy} onClick={()=>recheck(issue.branchId)}>Recheck status</Button></article>)}</div>
    {detail?.scope===scope&&<section className="communication-fixed-context" aria-label="Delivery Issue detail"><h2>Delivery Issue detail</h2><p>{detail.domain} · {detail.channel} · {detail.state}</p><p>{detail.reason}</p><p>Delivery evidence: {detail.deliveryState}. Bound Template version: {detail.templateVersion||'No render'}.</p><p>Retries preserve the same branch and render. A Reminder is new, separately authorized communication.</p><div className="notification-filters"><Button variant="secondary" disabled={busy} onClick={()=>recheck(detail.branchId)}>Recheck status</Button><Button disabled={busy||!detail.retryConfigured||!detail.attemptBudgetRemaining||known?.scope!==scope||known.branchId!==detail.branchId||known.state!=='not-applied'} onClick={()=>recheck(detail.branchId,'retry')}>Safe Retry</Button><Button variant="ghost" disabled={busy} onClick={()=>recheck(detail.branchId,'open-source')}>Open current source</Button></div><h3>Attempts</h3><ol>{detail.attempts.map((attempt,index)=><li key={index}>{attempt.state} · {new Date(attempt.startedAt).toLocaleString('en-NG')}</li>)}</ol><h3>Provider evidence</h3><ol>{detail.evidence.map((evidence,index)=><li key={index}>{evidence.kind} · {evidence.timeBasis==='PROVIDER'?'Provider time':'Observed time'}: {new Date(evidence.providerTime).toLocaleString('en-NG')}</li>)}</ol>{detail.historyPartial&&<p>Only the latest bounded evidence is shown here. Retained history has not been deleted.</p>}</section>}
    <p>Outcome uncertain is neither success nor failure. No “Mark delivered” control is provided.</p></section>;
}
